QUESTIONS = [
    "Help me brainstorm ideas for a startup",
    "I need creative ideas for a birthday party",
    "Let's brainstorm marketing strategies",
    "Give me ideas for my YouTube channel",
    "Help me think of blog post topics",
    "Brainstorm names for my new app",
    "I need ideas for a science fair project",
    "Let's brainstorm solutions to climate change",
    "Give me creative writing prompts",
    "Help me brainstorm fundraising ideas",
    "I need ideas for team building activities",
    "Let's brainstorm product features",
    "Give me ideas for social media content",
    "Help me think of business names",
    "Brainstorm ways to improve productivity",
    "I need ideas for a research paper topic",
    "Let's brainstorm costume ideas for Halloween",
    "Give me ideas for a mobile app",
    "Help me brainstorm gift ideas",
    "I need creative ideas for a presentation",
    "Let's brainstorm ways to save money",
    "Give me ideas for a podcast series",
    "Help me think of innovative solutions",
    "Brainstorm ideas for passive income",
    "I need ideas for a garden design",
    "Let's brainstorm content calendar topics",
    "Give me ideas for a novel",
    "Help me brainstorm vacation destinations",
    "I need ideas for a charity event",
    "Let's brainstorm new recipes",
    "Give me ideas for reducing waste",
    "Help me think of side hustle ideas",
    "Brainstorm slogans for my brand",
    "I need ideas for interior design",
    "Let's brainstorm workshop topics",
    "Give me ideas for a dating profile",
    "Help me brainstorm revenue streams",
    "I need creative ideas for advertising",
    "Let's brainstorm environmental initiatives",
    "Give me ideas for a fitness challenge",
    "Help me think of domain names",
    "Brainstorm ideas for a wedding theme",
    "I need ideas for a documentary",
    "Let's brainstorm customer retention strategies",
    "Give me ideas for a music playlist",
    "Help me brainstorm conversation starters",
    "I need ideas for a logo design",
    "Let's brainstorm ways to reduce stress",
    "Give me ideas for a thesis topic",
    "Help me think of icebreaker activities",
    "Brainstorm ideas for urban farming",
    "I need creative ideas for packaging",
    "Let's brainstorm community projects",
    "Give me ideas for a TikTok series",
    "Help me brainstorm dinner party themes",
    "I need ideas for a children's book",
    "Let's brainstorm ways to increase engagement",
    "Give me ideas for a subscription box",
    "Help me think of volunteer opportunities",
    "Brainstorm ideas for a fashion line",
    "I need creative ideas for networking",
    "Let's brainstorm sustainable practices",
    "Give me ideas for a mentorship program",
    "Help me brainstorm email subject lines",
    "I need ideas for a photography project",
    "Let's brainstorm innovations in education",
    "Give me ideas for a conference theme",
    "Help me think of incentive programs",
    "Brainstorm ideas for remote team engagement",
    "I need creative ideas for rebranding",
    "Let's brainstorm partnership opportunities",
    "Give me ideas for a game design",
    "Help me brainstorm wellness initiatives",
    "I need ideas for a art installation",
    "Let's brainstorm ways to improve customer service",
    "Give me ideas for a hackathon project",
    "Help me think of promotional campaigns",
    "Brainstorm ideas for reducing carbon footprint",
    "I need creative ideas for a festival",
    "Let's brainstorm digital transformation strategies",
    "Give me ideas for a retirement plan",
    "Brainstorm ideas for improving remote team collaboration",
    "Help me brainstorm topics for my tech conference talk",
    "Let's brainstorm solutions for reducing energy consumption",
    "Give me ideas for a community project",
    "Brainstorm features for an AI assistant",
    "I need ideas for optimizing workflow processes",
    "Let's brainstorm strategies for personal branding",
    "Give me ideas for a mentorship program",
    "Help me brainstorm innovative tech startups",
    "I need ideas for educational content",
    "Let's brainstorm ways to boost employee morale",
    "Give me ideas for a successful product launch",
    "Help me brainstorm crisis management strategies",
    "I need ideas for customer feedback initiatives",
    "Let's brainstorm ways to improve user experience",
    "Give me ideas for a networking event",
    "Help me brainstorm research paper topics",
    "I need ideas for sustainable business practices",
    "Let's brainstorm marketing campaign concepts",
    "Give me ideas for skill development workshops",
    "Help me brainstorm strategies for team growth",
    "I need ideas for innovation challenges",
    "Let's brainstorm creative problem-solving methods",
    "Give me ideas for building a personal brand",
    "Help me brainstorm industry disruption ideas",
    "I need ideas for improving work-life balance",
    "Let's brainstorm ways to increase engagement",
    "Give me ideas for a successful mentoring relationship",
    "Help me brainstorm content marketing strategies",
    "I need ideas for networking opportunities",
    "Let's brainstorm ways to foster creativity",
    "Give me ideas for a company retreat",
    "Help me brainstorm leadership development programs",
    "I need ideas for customer retention strategies",
    "Let's brainstorm new business models",
    "Give me ideas for a successful workshop",
    "Help me brainstorm ideas for scaling a business",
    "I need ideas for team building exercises",
    "Let's brainstorm ways to improve productivity",
    "Give me ideas for a successful collaboration",
    "Help me brainstorm strategies for market expansion",
    "I need ideas for employee engagement",
    "Let's brainstorm ways to innovate in my industry",
    "Give me ideas for a successful launch event",
    "Help me brainstorm partnership opportunities",
    "I need ideas for improving customer service",
    "Let's brainstorm ways to reduce costs",
    "Give me ideas for a successful rebrand",
    "Help me brainstorm ideas for community impact",
    "I need ideas for business expansion",
    "Brainstorm ideas for improving remote team collaboration",
    "Help me brainstorm topics for my tech conference talk",
    "Let's brainstorm solutions for reducing energy consumption",
    "Give me ideas for a community project",
    "Brainstorm features for an AI assistant",
    "I need ideas for optimizing workflow processes",
    "Let's brainstorm strategies for personal branding",
    "Give me ideas for a mentorship program",
    "Help me brainstorm innovative tech startups",
    "I need ideas for educational content",
    "Let's brainstorm ways to boost employee morale",
    "Give me ideas for a successful product launch",
    "Help me brainstorm crisis management strategies",
    "I need ideas for customer feedback initiatives",
    "Let's brainstorm ways to improve user experience",
    "Give me ideas for a networking event",
    "Help me brainstorm research paper topics",
    "I need ideas for sustainable business practices",
    "Let's brainstorm marketing campaign concepts",
    "Give me ideas for skill development workshops",
    "Help me brainstorm strategies for team growth",
    "I need ideas for innovation challenges",
    "Let's brainstorm creative problem-solving methods",
    "Give me ideas for building a personal brand",
    "Help me brainstorm industry disruption ideas",
    "I need ideas for improving work-life balance",
    "Let's brainstorm ways to increase engagement",
    "Give me ideas for a successful mentoring relationship",
    "Help me brainstorm content marketing strategies",
    "I need ideas for networking opportunities",
    "Let's brainstorm ways to foster creativity",
    "Give me ideas for a company retreat",
    "Help me brainstorm leadership development programs",
    "I need ideas for customer retention strategies",
    "Let's brainstorm new business models",
    "Give me ideas for a successful workshop",
    "Help me brainstorm ideas for scaling a business",
    "I need ideas for team building exercises",
    "Let's brainstorm ways to improve productivity",
    "Give me ideas for a successful collaboration",
    "Help me brainstorm strategies for market expansion",
    "I need ideas for employee engagement",
    "Let's brainstorm ways to innovate in my industry",
    "Give me ideas for a successful launch event",
    "Help me brainstorm partnership opportunities",
    "I need ideas for improving customer service",
    "Let's brainstorm ways to reduce costs",
    "Give me ideas for a successful rebrand",
    "Help me brainstorm ideas for community impact",
    "I need ideas for business expansion",
]
