QUESTIONS = [
    "What do you think about this?",
    "Tell me something interesting",
    "I'm feeling bored today",
    "What's your opinion on that?",
    "Let's have a conversation",
    "I had a great day today",
    "What should I do this weekend?",
    "Do you have any hobbies?",
    "I'm feeling a bit down",
    "That's really cool!",
    "What do you like to do?",
    "I can't believe that happened",
    "You're really helpful",
    "This is frustrating",
    "Tell me a joke",
    "I'm so excited!",
    "What's your favorite color?",
    "I need someone to talk to",
    "That makes sense",
    "I'm worried about tomorrow",
    "You know what I mean?",
    "This has been a tough week",
    "I'm so happy right now",
    "What would you do in my situation?",
    "I appreciate your help",
    "Life is good",
    "I'm confused about everything",
    "You're funny",
    "I need advice",
    "That's exactly what I was thinking",
    "I'm proud of myself today",
    "What's new with you?",
    "I can't decide what to do",
    "You understand me",
    "I'm stressed out",
    "That's a good point",
    "I learned something new today",
    "What's your take on this?",
    "I'm grateful for your support",
    "This is amazing!",
    "I don't know what to say",
    "You make a fair argument",
    "I'm looking forward to the weekend",
    "What's on your mind?",
    "I feel accomplished",
    "That's interesting",
    "I'm nervous about this",
    "You always know what to say",
    "I had the weirdest dream",
    "What do you think I should do?",
    "I'm feeling optimistic",
    "That's hilarious!",
    "I need a break",
    "You're very wise",
    "I'm curious about something",
    "That's so relatable",
    "I'm trying to stay positive",
    "What would make you happy?",
    "I'm feeling energetic today",
    "That's impressive",
    "I wish I knew earlier",
    "You give good advice",
    "I'm contemplating life",
    "That resonates with me",
    "I'm feeling creative",
    "What inspires you?",
    "I can't stop thinking about it",
    "You're right about that",
    "I'm feeling nostalgic",
    "That's beautiful",
    "I wonder what if...",
    "You have a good perspective",
    "I'm feeling peaceful",
    "That's thought-provoking",
    "I want to improve myself",
    "What matters most to you?",
    "I'm feeling adventurous",
    "That's mind-blowing",
    "I appreciate you",
    "Let's chat about your favorite hobbies",
    "What do you think about remote work?",
    "Tell me about your favorite book",
    "How do you spend your weekends?",
    "What's your opinion on social media?",
    "Let's talk about travel experiences",
    "What kind of music do you enjoy?",
    "How do you handle stress?",
    "What's your favorite cuisine?",
    "Tell me about a memorable moment",
    "What do you think about climate change?",
    "How do you stay motivated?",
    "What's your take on artificial intelligence?",
    "Let's discuss personal growth",
    "What's your favorite movie genre?",
    "How do you balance work and life?",
    "What brings you joy?",
    "Tell me about your career goals",
    "What's your philosophy on learning?",
    "How do you handle failure?",
    "What excites you about the future?",
    "Let's talk about relationships",
    "What's your creative outlet?",
    "How do you practice self-care?",
    "What's your stance on privacy?",
    "Tell me about a skill you want to learn",
    "What motivates you daily?",
    "How do you make important decisions?",
    "What's your favorite way to relax?",
    "Let's discuss innovation",
    "What's your view on education?",
    "How do you handle conflicts?",
    "What inspires you?",
    "Tell me about your biggest achievement",
    "What's your perspective on success?",
    "How do you stay organized?",
    "What's your favorite technology?",
    "Let's talk about ethics",
    "How do you approach problem-solving?",
    "What's your take on entrepreneurship?",
    "Tell me about your role models",
    "What's your vision for the future?",
    "How do you stay informed?",
    "What's your favorite way to spend time?",
    "Let's discuss collaboration",
    "What challenges excite you?",
    "How do you measure success?",
    "What's your take on networking?",
    "Tell me about your dreams",
    "What makes a good leader?",
    "Let's chat about your favorite hobbies",
    "What do you think about remote work?",
    "Tell me about your favorite book",
    "How do you spend your weekends?",
    "What's your opinion on social media?",
    "Let's talk about travel experiences",
    "What kind of music do you enjoy?",
    "How do you handle stress?",
    "What's your favorite cuisine?",
    "Tell me about a memorable moment",
    "What do you think about climate change?",
    "How do you stay motivated?",
    "What's your take on artificial intelligence?",
    "Let's discuss personal growth",
    "What's your favorite movie genre?",
    "How do you balance work and life?",
    "What brings you joy?",
    "Tell me about your career goals",
    "What's your philosophy on learning?",
    "How do you handle failure?",
    "What excites you about the future?",
    "Let's talk about relationships",
    "What's your creative outlet?",
    "How do you practice self-care?",
    "What's your stance on privacy?",
    "Tell me about a skill you want to learn",
    "What motivates you daily?",
    "How do you make important decisions?",
    "What's your favorite way to relax?",
    "Let's discuss innovation",
    "What's your view on education?",
    "How do you handle conflicts?",
    "What inspires you?",
    "Tell me about your biggest achievement",
    "What's your perspective on success?",
    "How do you stay organized?",
    "What's your favorite technology?",
    "Let's talk about ethics",
    "How do you approach problem-solving?",
    "What's your take on entrepreneurship?",
    "Tell me about your role models",
    "What's your vision for the future?",
    "How do you stay informed?",
    "What's your favorite way to spend time?",
    "Let's discuss collaboration",
    "What challenges excite you?",
    "How do you measure success?",
    "What's your take on networking?",
    "Tell me about your dreams",
    "What makes a good leader?",
]
