TRAINING_DATA = [
    {"question": "Write a Python function to sort a list", "think": "<think>Need a sorting function. Consider: 1) Use built-in sort or implement algorithm, 2) Handle edge cases, 3) Return sorted list</think>"},
    {"question": "How do I create a REST API in Node.js?", "think": "<think>REST API requires: 1) Web framework (Express), 2) Routing for endpoints, 3) Request/response handling, 4) Database connection</think>"},
    {"question": "Show me an example of a class in Python", "think": "<think>Python class structure: 1) Use 'class' keyword, 2) Define __init__ constructor, 3) Add methods, 4) Create instances</think>"},
    {"question": "Write a function to reverse a string in JavaScript", "think": "<think>String reversal: 1) Convert to array, 2) Reverse array elements, 3) Join back to string</think>"},
    {"question": "How do I read a CSV file in Python?", "think": "<think>CSV reading: 1) Import csv module, 2) Open file, 3) Create reader, 4) Iterate through rows, 5) Parse data</think>"},
    {"question": "Create a React component for a button", "think": "<think>React button component: 1) Define functional component, 2) Accept props for text/onClick, 3) Return JSX element, 4) Export component</think>"},
    {"question": "Write SQL query to join two tables", "think": "<think>SQL join: 1) Identify join type (INNER/LEFT), 2) Specify tables, 3) Define join condition, 4) Select columns needed</think>"},
    {"question": "Show me how to use async/await in JavaScript", "think": "<think>Async/await: 1) Declare async function, 2) Use await for promises, 3) Handle errors with try/catch, 4) Return result</think>"},
]

# Keep QUESTIONS for backward compatibility
QUESTIONS = [q["question"] for q in TRAINING_DATA]
    "Show me how to use D3.js for data visualization",
    "How do I implement rate limiting in an API?",
    "How do I implement machine learning models?",
    "Write a script to automate file backups",
    "Show me how to use Docker and Kubernetes",
    "How do I build a web scraper with BeautifulSoup?",
    "Write a Python program for image processing",
    "How do I implement a payment system?",
    "Create a real-time chat application",
    "How do I set up continuous integration?",
    "Write a function to optimize database queries",
    "Show me how to use GraphQL APIs",
    "How do I build a mobile app with React Native?",
    "Write a script to analyze log files",
    "How do I implement caching strategies?",
    "Create a recommendation system",
    "How do I use microservices architecture?",
    "Write a program for data visualization",
    "Show me how to implement search functionality",
    "How do I build an e-commerce platform?",
    "Write a script for web automation",
    "How do I implement version control workflows?",
    "Create a machine learning pipeline",
    "How do I optimize code performance?",
    "Write a function for text processing",
    "Show me how to use cloud services",
    "How do I implement security best practices?",
    "Write a program for data analysis",
    "How do I build a dashboard application?",
    "Create a notification system",
    "How do I implement testing strategies?",
    "Write a script for system monitoring",
    "Show me how to use APIs effectively",
    "How do I build a content management system?",
    "Write a function for handling errors",
    "How do I implement database migrations?",
    "Create a scheduling system",
    "How do I optimize memory usage?",
    "Write a program for file compression",
    "Show me how to use design patterns",
    "How do I build a real-time application?",
    "Write a script for data validation",
    "How do I implement load balancing?",
    "Create a user authentication system",
    "How do I optimize network requests?",
    "Write a function for parallel processing",
    "Show me how to use message queues",
    "How do I build a recommendation engine?",
    "Write a program for natural language processing",
    "How do I implement serverless architecture?",
    "Create an analytics system",
    "How do I optimize database indexes?",
    "How do I implement machine learning models?",
    "Write a script to automate file backups",
    "Show me how to use Docker and Kubernetes",
    "How do I build a web scraper with BeautifulSoup?",
    "Write a Python program for image processing",
    "How do I implement a payment system?",
    "Create a real-time chat application",
    "How do I set up continuous integration?",
    "Write a function to optimize database queries",
    "Show me how to use GraphQL APIs",
    "How do I build a mobile app with React Native?",
    "Write a script to analyze log files",
    "How do I implement caching strategies?",
    "Create a recommendation system",
    "How do I use microservices architecture?",
    "Write a program for data visualization",
    "Show me how to implement search functionality",
    "How do I build an e-commerce platform?",
    "Write a script for web automation",
    "How do I implement version control workflows?",
    "Create a machine learning pipeline",
    "How do I optimize code performance?",
    "Write a function for text processing",
    "Show me how to use cloud services",
    "How do I implement security best practices?",
    "Write a program for data analysis",
    "How do I build a dashboard application?",
    "Create a notification system",
    "How do I implement testing strategies?",
    "Write a script for system monitoring",
    "Show me how to use APIs effectively",
    "How do I build a content management system?",
    "Write a function for handling errors",
    "How do I implement database migrations?",
    "Create a scheduling system",
    "How do I optimize memory usage?",
    "Write a program for file compression",
    "Show me how to use design patterns",
    "How do I build a real-time application?",
    "Write a script for data validation",
    "How do I implement load balancing?",
    "Create a user authentication system",
    "How do I optimize network requests?",
    "Write a function for parallel processing",
    "Show me how to use message queues",
    "How do I build a recommendation engine?",
    "Write a program for natural language processing",
    "How do I implement serverless architecture?",
    "Create an analytics system",
    "How do I optimize database indexes?",
]
