TRAINING_DATA = [
    {"question": "Walk me through how to solve this problem step by step", "think": "<think>CoT requires: 1) Break problem into steps, 2) Define each step clearly, 3) Show progression, 4) Verify intermediate results</think>"},
    {"question": "Explain your reasoning for this answer", "think": "<think>Reasoning explanation needs: 1) State the conclusion, 2) Provide supporting evidence, 3) Link evidence to conclusion, 4) Address counterarguments</think>"},
    {"question": "Let's think through this carefully", "think": "<think>Careful thinking requires: 1) Consider all aspects, 2) Identify assumptions, 3) Check logical validity, 4) Draw conclusions cautiously</think>"},
    {"question": "Show me your thought process", "think": "<think>Thought process transparency: 1) Externalize thinking steps, 2) Explain decision points, 3) Show why alternatives rejected, 4) Justify final choice</think>"},
    {"question": "Explain step by step how you arrived at this conclusion", "think": "<think>Step-by-step explanation: 1) Identify problem, 2) List assumptions, 3) Show calculations/logic, 4) Present conclusion with evidence</think>"},
    {"question": "Think through this problem logically", "think": "<think>Logical thinking: 1) Define the problem clearly, 2) Use valid inference rules, 3) Build logical chain, 4) Check for consistency</think>"},
    {"question": "Can you break down your reasoning?", "think": "<think>Breaking down reasoning: 1) Identify main argument, 2) Separate into sub-arguments, 3) Explain each component, 4) Show how they connect</think>"},
]

# Keep QUESTIONS for backward compatibility
QUESTIONS = [q["question"] for q in TRAINING_DATA]
    "Walk through how you eliminated errors",
    "Show your verification process",
    "Let's trace the reasoning from start to finish",
    "Explain each inference you made",
    "Think through the problem with me",
    "Show me how you checked your work",
    "Let's build the solution incrementally",
    "Explain your step-wise approach",
    "Walk through your thought experiment",
    "Show how you arrived at each intermediate conclusion",
    "Let's reason about this carefully and deliberately",
    "Explain your logical pathway",
    "Think about what happens at each stage",
    "Show me your decision-making process",
    "Let's work through the logic tree",
    "Explain how you know each step is correct",
    "Walk me through your validation steps",
    "Show the proof step by step",
    "Let's think about this rationally",
    "Explain your reasoning chain clearly",
    "Think through how you can verify this",
    "Let's think step by step about quantum mechanics",
    "Chain of thought: How does evolution work?",
    "Break down the process of photosynthesis systematically",
    "Step by step: What causes economic inflation?",
    "Let's reason through the problem of climate change",
    "Chain of thought reasoning about artificial general intelligence",
    "Systematically explain how neural networks learn",
    "Step by step analysis of blockchain technology",
    "Let's think carefully about the nature of consciousness",
    "Chain of thought: How do vaccines work?",
    "Break down the steps of scientific research methodology",
    "Step by step: How does DNA store information?",
    "Let's reason through the implications of AI advancement",
    "Chain of thought analysis of supply chain logistics",
    "Systematically explain international trade dynamics",
    "Step by step reasoning about pandemic spread",
    "Let's think through the ethics of genetic engineering",
    "Chain of thought: How do markets reach equilibrium?",
    "Break down the process of language acquisition",
    "Step by step analysis of mathematical proofs",
    "Let's reason about the causes of social inequality",
    "Chain of thought thinking about sustainable energy",
    "Systematically explain how human memory works",
    "Step by step: How does the immune system function?",
    "Let's think through climate modeling predictions",
    "Chain of thought reasoning about resource allocation",
    "Break down the factors affecting education outcomes",
    "Step by step analysis of international conflicts",
    "Let's reason through the impacts of urbanization",
    "Chain of thought thinking about biodiversity loss",
    "Systematically explain cybersecurity threats",
    "Step by step: How does the circular economy work?",
    "Let's think through the effects of automation",
    "Chain of thought analysis of financial markets",
    "Break down the process of drug development",
    "Step by step reasoning about political polarization",
    "Let's reason about the future of work",
    "Chain of thought thinking about water scarcity",
    "Systematically explain the aging process",
    "Step by step: How does space exploration progress?",
    "Let's think through the challenges of healthcare",
    "Chain of thought reasoning about cultural change",
    "Break down the factors of successful innovation",
    "Step by step analysis of supply and demand",
    "Let's reason about the future of transportation",
    "Chain of thought thinking about mental health",
    "Systematically explain ecosystem dynamics",
    "Step by step: How do legal systems function?",
    "Let's think through the impacts of globalization",
    "Let's think step by step about quantum mechanics",
    "Chain of thought: How does evolution work?",
    "Break down the process of photosynthesis systematically",
    "Step by step: What causes economic inflation?",
    "Let's reason through the problem of climate change",
    "Chain of thought reasoning about artificial general intelligence",
    "Systematically explain how neural networks learn",
    "Step by step analysis of blockchain technology",
    "Let's think carefully about the nature of consciousness",
    "Chain of thought: How do vaccines work?",
    "Break down the steps of scientific research methodology",
    "Step by step: How does DNA store information?",
    "Let's reason through the implications of AI advancement",
    "Chain of thought analysis of supply chain logistics",
    "Systematically explain international trade dynamics",
    "Step by step reasoning about pandemic spread",
    "Let's think through the ethics of genetic engineering",
    "Chain of thought: How do markets reach equilibrium?",
    "Break down the process of language acquisition",
    "Step by step analysis of mathematical proofs",
    "Let's reason about the causes of social inequality",
    "Chain of thought thinking about sustainable energy",
    "Systematically explain how human memory works",
    "Step by step: How does the immune system function?",
    "Let's think through climate modeling predictions",
    "Chain of thought reasoning about resource allocation",
    "Break down the factors affecting education outcomes",
    "Step by step analysis of international conflicts",
    "Let's reason through the impacts of urbanization",
    "Chain of thought thinking about biodiversity loss",
    "Systematically explain cybersecurity threats",
    "Step by step: How does the circular economy work?",
    "Let's think through the effects of automation",
    "Chain of thought analysis of financial markets",
    "Break down the process of drug development",
    "Step by step reasoning about political polarization",
    "Let's reason about the future of work",
    "Chain of thought thinking about water scarcity",
    "Systematically explain the aging process",
    "Step by step: How does space exploration progress?",
    "Let's think through the challenges of healthcare",
    "Chain of thought reasoning about cultural change",
    "Break down the factors of successful innovation",
    "Step by step analysis of supply and demand",
    "Let's reason about the future of transportation",
    "Chain of thought thinking about mental health",
    "Systematically explain ecosystem dynamics",
    "Step by step: How do legal systems function?",
    "Let's think through the impacts of globalization",
    "Chain of thought reasoning about human rights",
]
