QUESTIONS = [
    "Review my essay and provide feedback",
    "Critique this business plan",
    "What are the flaws in this argument?",
    "Review my code and suggest improvements",
    "Critique this design mockup",
    "What's wrong with this approach?",
    "Review my resume",
    "Critique this marketing strategy",
    "What are weaknesses in this proposal?",
    "Review my presentation slides",
    "Critique this website design",
    "What could be improved in this writing?",
    "Review my research methodology",
    "Critique this user interface",
    "What are the problems with this solution?",
    "Review my cover letter",
    "Critique this architectural design",
    "What's missing from this analysis?",
    "Review my investment portfolio",
    "Critique this advertising campaign",
    "What are the gaps in this plan?",
    "Review my LinkedIn profile",
    "Critique this data visualization",
    "What are the logical fallacies here?",
    "Review my budget proposal",
    "Critique this product design",
    "What could go wrong with this strategy?",
    "Review my thesis statement",
    "Critique this mobile app",
    "What are the ethical issues in this approach?",
    "Review my project timeline",
    "Critique this brand identity",
    "What are the security vulnerabilities?",
    "Review my grant application",
    "Critique this training program",
    "What are the usability issues?",
    "Review my business email",
    "Critique this policy document",
    "What are the weaknesses in this theory?",
    "Review my pitch deck",
    "Critique this organizational structure",
    "What's inefficient about this process?",
    "Review my job description",
    "Critique this customer service approach",
    "What are the risks in this decision?",
    "Review my technical documentation",
    "Critique this pricing strategy",
    "What's unclear in this explanation?",
    "Review my mission statement",
    "Critique this supply chain design",
    "What are the accessibility problems?",
    "Review my meeting agenda",
    "Critique this HR policy",
    "What's biased in this survey?",
    "Review my social media strategy",
    "Critique this onboarding process",
    "What are the scalability issues?",
    "Review my performance metrics",
    "Critique this crisis communication plan",
    "What's ineffective about this teaching method?",
    "Review my API documentation",
    "Critique this compensation package",
    "What are the sustainability concerns?",
    "Review my partnership agreement",
    "Critique this change management plan",
    "What's problematic about this assumption?",
    "Review my SEO strategy",
    "Critique this diversity initiative",
    "What are the compliance issues?",
    "Review my customer journey map",
    "Critique this quality assurance process",
    "What's missing from this requirements document?",
    "Review my content calendar",
    "Critique this conflict resolution approach",
    "What are the privacy concerns?",
    "Review my sales funnel",
    "Critique this innovation strategy",
    "What's wrong with this data model?",
    "Review my employee handbook",
    "Critique this sustainability report",
    "What are the maintenance challenges?",
    "Review my stakeholder analysis",
    "Review this response for accuracy",
    "Constitutional AI analysis of this statement",
    "Self-critique this argument for logical fallacies",
    "Review this explanation for clarity",
    "CAI assessment: Does this follow ethical principles?",
    "Critique the structure of this reasoning",
    "Self-review: Is this response helpful?",
    "Constitutional analysis: Evaluate fairness",
    "Review for potential biases",
    "Critique the evidence supporting this claim",
    "Self-assess: Is this response complete?",
    "Review for potential harms",
    "Constitutional check: Does this respect rights?",
    "Critique the coherence of this argument",
    "Self-review: Is this response honest?",
    "Review for factual accuracy",
    "Critique the assumptions made",
    "CAI evaluation: Check for fairness",
    "Self-assess: Is this response balanced?",
    "Review for potential misunderstandings",
    "Critique the logical flow",
    "Review for consistency",
    "Self-review: Is this response helpful and harmless?",
    "Constitutional analysis: Evaluate transparency",
    "Critique the reasoning quality",
    "Review for completeness",
    "Self-assess: Are all perspectives considered?",
    "Constitutional check: Is this respectful?",
    "Critique the supporting evidence",
    "Review for potential conflicts of interest",
    "Self-review: Is the tone appropriate?",
    "Constitutional analysis: Evaluate accountability",
    "Critique the practical implications",
    "Review for contradictions",
    "Self-assess: Is this response truthful?",
    "Review for accessibility",
    "Critique the scope of the response",
    "Constitutional check: Evaluate justice",
    "Self-review: Could this be harmful?",
    "Review for potential misuse",
    "Critique the originality of the thinking",
    "Self-assess: Is this response well-reasoned?",
    "Constitutional analysis: Check for inclusivity",
    "Review for potential oversimplification",
    "Critique the depth of analysis",
    "Self-review: Have I addressed all concerns?",
    "Review for cultural sensitivity",
    "Review this response for accuracy",
    "Constitutional AI analysis of this statement",
    "Self-critique this argument for logical fallacies",
    "Review this explanation for clarity",
    "CAI assessment: Does this follow ethical principles?",
    "Critique the structure of this reasoning",
    "Self-review: Is this response helpful?",
    "Constitutional analysis: Evaluate fairness",
    "Review for potential biases",
    "Critique the evidence supporting this claim",
    "Self-assess: Is this response complete?",
    "Review for potential harms",
    "Constitutional check: Does this respect rights?",
    "Critique the coherence of this argument",
    "Self-review: Is this response honest?",
    "Review for factual accuracy",
    "Critique the assumptions made",
    "CAI evaluation: Check for fairness",
    "Self-assess: Is this response balanced?",
    "Review for potential misunderstandings",
    "Critique the logical flow",
    "Review for consistency",
    "Self-review: Is this response helpful and harmless?",
    "Constitutional analysis: Evaluate transparency",
    "Critique the reasoning quality",
    "Review for completeness",
    "Self-assess: Are all perspectives considered?",
    "Constitutional check: Is this respectful?",
    "Critique the supporting evidence",
    "Review for potential conflicts of interest",
    "Self-review: Is the tone appropriate?",
    "Constitutional analysis: Evaluate accountability",
    "Critique the practical implications",
    "Review for contradictions",
    "Self-assess: Is this response truthful?",
    "Review for accessibility",
    "Critique the scope of the response",
    "Constitutional check: Evaluate justice",
    "Self-review: Could this be harmful?",
    "Review for potential misuse",
    "Critique the originality of the thinking",
    "Self-assess: Is this response well-reasoned?",
    "Constitutional analysis: Check for inclusivity",
    "Review for potential oversimplification",
    "Critique the depth of analysis",
    "Self-review: Have I addressed all concerns?",
    "Review for cultural sensitivity",
    "Critique the credibility of sources",
    "Self-assess: Does this follow logic?",
]
