QUESTIONS = [
    "explearn What is gravity? | Gravity is a fundamental force | F=mg",
    "teach: What is DNA? | DNA is a double helix | genetic code",
    "explearn math: What is pi? | Pi is ratio of circumference | 3.14159",
    "explanatory learning quantum | quantum states superpose | wave function",
    "explearn show my store",
    "explearn test",
    "self test explanatory learning",
    "explearn What is entropy? | Entropy measures disorder | second law",
    "teach: What is a derivative? | Rate of change of function | f prime of x",
    "explearn: What is neural network? | Layers of connected neurons | learns patterns",
    "teach me about recursion | A function calling itself | base case terminates",
    "explearn: What is photosynthesis? | Plants convert light to energy | 6CO2+6H2O",
    "teach: What is relativity? | Space and time are relative | E=mc squared",
    "explearn: What is consciousness? | Subjective experience of awareness | qualia",
    "teach about evolution | Species change over generations | natural selection",
    "explearn: What is Bayes theorem? | Conditional probability update | P(A|B)",
    "teach me gradient descent | Optimization by following gradient | minimize loss",
    "explearn: What is a transformer? | Attention-based neural network | self attention",
    "teach: What is quantum mechanics? | Physics of subatomic particles | uncertainty",
    "explearn: What is entropy? | Information theoretic measure | bits of information",
    "teach about backpropagation | Gradient computation for training | chain rule",
    "explearn triple: question explanation answer",
    "add to knowledge base using explearn",
    "teach me using question pipe explanation pipe answer",
    "show the explearn store",
    "list all explearn entries",
    "explearn self test",
    "run explanatory learning test",
    "store this as explearn triple",
    "Explearn: What is photosynthesis? | Process where plants convert light energy | Through chlorophyll absorption",
    "Teach: What is gravity? | Force attracting objects | Proportional to mass, inversely to distance squared",
    "Explearn: What are electrons? | Negatively charged particles | Orbit nucleus in atoms",
    "Explearn: What is thermodynamics? | Study of heat and energy | Three laws govern energy transfer",
    "Teach: What is evolution? | Process of biological change | Natural selection drives adaptation",
    "Explearn: What is DNA? | Double helix molecule | Stores genetic information for life",
    "Teach: What is photosynthesis? | Energy conversion process | Transforms light into chemical energy",
    "Explearn: What are proteins? | Amino acid chains | Perform diverse biological functions",
    "Teach: What is osmosis? | Water movement across membranes | Driven by concentration gradients",
    "Explearn: What is mitosis? | Cell division process | Produces two identical daughter cells",
    "Teach: What is the water cycle? | Continuous water circulation | Evaporation, condensation, precipitation",
    "Explearn: What are organelles? | Cell structures with functions | Include mitochondria, lysosomes",
    "Teach: What is photon? | Packet of light energy | Foundation of quantum mechanics",
    "Explearn: What is metabolism? | Chemical reactions in organisms | Builds or breaks down molecules",
    "Teach: What is enzyme? | Biological catalyst | Speeds up chemical reactions",
    "Explearn: What is neuron? | Nerve cell type | Transmits electrical and chemical signals",
    "Teach: What is antibody? | Immune protein | Recognizes and neutralizes pathogens",
    "Explearn: What is carbohydrate? | Organic molecule | Provides energy and structure",
    "Teach: What is lipid? | Hydrophobic molecule | Stores energy and forms membranes",
    "Explearn: What is hormone? | Signaling molecule | Regulates bodily functions",
    "Teach: What is ecosystem? | Biological community and environment | Organisms interact with surroundings",
    "Explearn: What is ATP? | Energy currency of cells | Powers cellular processes",
    "Teach: What is species? | Group of similar organisms | Can reproduce together",
    "Explearn: What is fossil? | Preserved remains of organisms | Provides evolutionary evidence",
    "Teach: What is symbiosis? | Close organism relationship | Includes mutualism and parasitism",
    "Explearn: What is adaptation? | Trait improving survival | Result of natural selection",
    "Teach: What is biodiversity? | Variety of life forms | Measured at multiple levels",
    "Explearn: What is mutation? | Change in DNA sequence | Source of genetic variation",
    "Teach: What is predator? | Animal that hunts others | Controls prey populations",
    "Explearn: What is prey? | Animal hunted for food | Develops defensive adaptations",
    "Teach: What is niche? | Organism's ecological role | Unique in each environment",
    "Explearn: What is succession? | Ecological change over time | Communities develop gradually",
    "Teach: What is pollination? | Pollen transfer process | Enables plant reproduction",
    "Explearn: What is decomposer? | Organism breaking down dead matter | Returns nutrients to soil",
    "Teach: What is predation? | Hunting behavior | Key predator-prey relationship",
    "Explearn: What is competition? | Organisms seeking same resources | Drives evolution",
    "Teach: What is migration? | Large-scale movement of animals | Follows seasonal patterns",
    "Explearn: What is hibernation? | Extended dormancy period | Conserves energy in winter",
    "Teach: What is camouflage? | Blending with environment | Predator avoidance strategy",
    "Explearn: What is metamorphosis? | Dramatic body transformation | Seen in insects and amphibians",
    "Teach: What is taxonomy? | Classification of organisms | Uses hierarchical system",
    "Explearn: What is genome? | Complete genetic information | Contains all organism blueprints",
    "Teach: What is chromosome? | DNA-containing structure | Carries genetic information",
    "Explearn: What is meiosis? | Sex cell formation process | Produces gametes",
    "Teach: What is phenotype? | Observable organism traits | Result of genetics and environment",
    "Explearn: What is genotype? | Genetic makeup of organism | Not always visible",
    "Teach: What is allele? | Gene variant at locus | Determines trait expressions",
    "Explearn: What is dominant trait? | Expressed even heterozygous | Masks recessive traits",
    "Teach: What is recessive trait? | Only expressed homozygous | Masked by dominant",
    "Explearn: What is inheritance? | Trait passing through generations | Follows genetic laws",
    "retrieve explearn knowledge",
    "Explearn: What is photosynthesis? | Process where plants convert light energy | Through chlorophyll absorption",
    "Teach: What is gravity? | Force attracting objects | Proportional to mass, inversely to distance squared",
    "Explearn: What are electrons? | Negatively charged particles | Orbit nucleus in atoms",
    "Explearn: What is thermodynamics? | Study of heat and energy | Three laws govern energy transfer",
    "Teach: What is evolution? | Process of biological change | Natural selection drives adaptation",
    "Explearn: What is DNA? | Double helix molecule | Stores genetic information for life",
    "Teach: What is photosynthesis? | Energy conversion process | Transforms light into chemical energy",
    "Explearn: What are proteins? | Amino acid chains | Perform diverse biological functions",
    "Teach: What is osmosis? | Water movement across membranes | Driven by concentration gradients",
    "Explearn: What is mitosis? | Cell division process | Produces two identical daughter cells",
    "Teach: What is the water cycle? | Continuous water circulation | Evaporation, condensation, precipitation",
    "Explearn: What are organelles? | Cell structures with functions | Include mitochondria, lysosomes",
    "Teach: What is photon? | Packet of light energy | Foundation of quantum mechanics",
    "Explearn: What is metabolism? | Chemical reactions in organisms | Builds or breaks down molecules",
    "Teach: What is enzyme? | Biological catalyst | Speeds up chemical reactions",
    "Explearn: What is neuron? | Nerve cell type | Transmits electrical and chemical signals",
    "Teach: What is antibody? | Immune protein | Recognizes and neutralizes pathogens",
    "Explearn: What is carbohydrate? | Organic molecule | Provides energy and structure",
    "Teach: What is lipid? | Hydrophobic molecule | Stores energy and forms membranes",
    "Explearn: What is hormone? | Signaling molecule | Regulates bodily functions",
    "Teach: What is ecosystem? | Biological community and environment | Organisms interact with surroundings",
    "Explearn: What is ATP? | Energy currency of cells | Powers cellular processes",
    "Teach: What is species? | Group of similar organisms | Can reproduce together",
    "Explearn: What is fossil? | Preserved remains of organisms | Provides evolutionary evidence",
    "Teach: What is symbiosis? | Close organism relationship | Includes mutualism and parasitism",
    "Explearn: What is adaptation? | Trait improving survival | Result of natural selection",
    "Teach: What is biodiversity? | Variety of life forms | Measured at multiple levels",
    "Explearn: What is mutation? | Change in DNA sequence | Source of genetic variation",
    "Teach: What is predator? | Animal that hunts others | Controls prey populations",
    "Explearn: What is prey? | Animal hunted for food | Develops defensive adaptations",
    "Teach: What is niche? | Organism's ecological role | Unique in each environment",
    "Explearn: What is succession? | Ecological change over time | Communities develop gradually",
    "Teach: What is pollination? | Pollen transfer process | Enables plant reproduction",
    "Explearn: What is decomposer? | Organism breaking down dead matter | Returns nutrients to soil",
    "Teach: What is predation? | Hunting behavior | Key predator-prey relationship",
    "Explearn: What is competition? | Organisms seeking same resources | Drives evolution",
    "Teach: What is migration? | Large-scale movement of animals | Follows seasonal patterns",
    "Explearn: What is hibernation? | Extended dormancy period | Conserves energy in winter",
    "Teach: What is camouflage? | Blending with environment | Predator avoidance strategy",
    "Explearn: What is metamorphosis? | Dramatic body transformation | Seen in insects and amphibians",
    "Teach: What is taxonomy? | Classification of organisms | Uses hierarchical system",
    "Explearn: What is genome? | Complete genetic information | Contains all organism blueprints",
    "Teach: What is chromosome? | DNA-containing structure | Carries genetic information",
    "Explearn: What is meiosis? | Sex cell formation process | Produces gametes",
    "Teach: What is phenotype? | Observable organism traits | Result of genetics and environment",
    "Explearn: What is genotype? | Genetic makeup of organism | Not always visible",
    "Teach: What is allele? | Gene variant at locus | Determines trait expressions",
    "Explearn: What is dominant trait? | Expressed even heterozygous | Masks recessive traits",
    "Teach: What is recessive trait? | Only expressed homozygous | Masked by dominant",
    "Explearn: What is inheritance? | Trait passing through generations | Follows genetic laws",
]
