QUESTIONS = [
    "Check this sentence: Their going to the store",
    "Is this grammatically correct: Me and John went shopping",
    "Fix this: I don't have no money",
    "Correct my grammar: She don't like pizza",
    "Is this right: Between you and I",
    "Check grammar: The dog wagged it's tail",
    "Correct this sentence: Could of been better",
    "Is this correct: Your beautiful",
    "Fix: Who should I give this to?",
    "Check: I seen him yesterday",
    "Correct: Less people came than expected",
    "Is this right: Each of the students have a book",
    "Fix this grammar: Me myself did it",
    "Check: I could care less",
    "Correct: The data is corrupted",
    "Is this proper: Hopefully, it will rain",
    "Fix: I feel badly about it",
    "Check this: Neither of them are here",
    "Correct: That's her and I in the photo",
    "Is this right: I'm doing good",
    "Fix the grammar: Between you and he",
    "Check: If I was rich",
    "Correct this: Irregardless of what happens",
    "Is this correct: Who did you see?",
    "Fix: The reason is because",
    "Check grammar: Literally dying right now",
    "Correct: Try and do better",
    "Is this right: You was there",
    "Fix: Each person should bring their book",
    "Check: I could of sworn",
    "Correct this: For all intensive purposes",
    "Is this proper English: Ain't no way",
    "Fix grammar: Where are you at?",
    "Check: I and my friends",
    "Correct: Your going too fast",
    "Is this right: They was happy",
    "Fix: It's been a long time since I seen you",
    "Check this sentence: There over their with they're dog",
    "Correct: I should of known",
    "Is this correct: Can I borrow you a pen?",
    "Fix: Him and me are friends",
    "Check: She's taller then me",
    "Correct this: I feel nauseous",
    "Is this grammatically right: Whom is calling?",
    "Fix: Myself will attend the meeting",
    "Check grammar: That don't make sense",
    "Correct: Everybody brought their lunch",
    "Is this proper: To who it may concern",
    "Fix this: I have went there before",
    "Check: Between the three of us",
    "Correct: Me and her went shopping",
    "Is this correct: I done finished my homework",
    "Fix grammar: She walks slow",
    "Check: More faster than before",
    "Correct this: I have less friends now",
    "Is this right: I'm suppose to go",
    "Fix: The team are winning",
    "Check grammar: If I would have known",
    "Correct: It's raining outside, I should of brought an umbrella",
    "Is this sentence correct: Who's book is this?",
    "Fix: We was going to the mall",
    "Check: Good job on you!",
    "Correct this: I'm not sure but I think its broken",
    "Is this grammatically correct: Thats what I think",
    "Fix: How come your late?",
    "Check grammar: There's many reasons",
    "Correct: I and my sister",
    "Is this right: I could of done better",
    "Fix this: The number of people are increasing",
    "Check: Him and I went together",
    "Correct grammar: Who's turn is it?",
    "Is this proper: I seen it with my own eyes",
    "Fix: Your the best",
    "Check this: Alot of people",
    "Correct: I would of called you",
    "Is this sentence right: Me and him are brothers",
    "Fix grammar: She sing beautifully",
    "Check: Its a beautiful day",
    "Correct this: Your not going to believe this",
    "Is this correct: I have ate already",
    "Generate a sentence about artificial intelligence",
    "Create a grammatically perfect statement about science",
    "Make a sentence describing nature",
    "Generate a complex sentence with multiple clauses",
    "Create a sentence using passive voice",
    "Make a sentence with advanced vocabulary",
    "Generate a sentence about technology",
    "Create a metaphorical sentence",
    "Make a sentence describing emotions",
    "Generate a sentence with proper punctuation",
    "Create a sentence using conditional mood",
    "Make a sentence with alliteration",
    "Generate a sentence about history",
    "Create a descriptive sentence",
    "Make a sentence using relative clauses",
    "Generate a sentence with parallel structure",
    "Create a sentence about future events",
    "Make a sentence with proper subject-verb agreement",
    "Generate a sentence with varied word order",
    "Create a sentence using gerunds",
    "Make a sentence about abstract concepts",
    "Generate a sentence with dependent clauses",
    "Create a sentence using infinitives",
    "Make a sentence describing time",
    "Generate a sentence with proper tense consistency",
    "Create a sentence using participles",
    "Make a sentence about relationships",
    "Generate a sentence with coordinating conjunctions",
    "Create a sentence about achievements",
    "Make a sentence with subordinating conjunctions",
    "Generate a sentence using metaphors",
    "Create a sentence about challenges",
    "Make a sentence with proper comma placement",
    "Generate a sentence using similes",
    "Create a sentence about innovation",
    "Make a sentence with varied punctuation",
    "Generate a sentence about exploration",
    "Create a sentence using noun phrases",
    "Make a sentence describing transitions",
    "Generate a sentence with complex syntax",
    "Create a sentence about discovery",
    "Make a sentence using adjective clauses",
    "Generate a sentence about growth",
    "Create a sentence with proper capitalization",
    "Make a sentence about transformation",
    "Generate a sentence using prepositional phrases",
    "Create a sentence about connections",
    "Make a sentence describing moments",
    "Generate a sentence with proper voice",
    "Create a sentence about experiences",
    "Generate a sentence about artificial intelligence",
    "Create a grammatically perfect statement about science",
    "Make a sentence describing nature",
    "Generate a complex sentence with multiple clauses",
    "Create a sentence using passive voice",
    "Make a sentence with advanced vocabulary",
    "Generate a sentence about technology",
    "Create a metaphorical sentence",
    "Make a sentence describing emotions",
    "Generate a sentence with proper punctuation",
    "Create a sentence using conditional mood",
    "Make a sentence with alliteration",
    "Generate a sentence about history",
    "Create a descriptive sentence",
    "Make a sentence using relative clauses",
    "Generate a sentence with parallel structure",
    "Create a sentence about future events",
    "Make a sentence with proper subject-verb agreement",
    "Generate a sentence with varied word order",
    "Create a sentence using gerunds",
    "Make a sentence about abstract concepts",
    "Generate a sentence with dependent clauses",
    "Create a sentence using infinitives",
    "Make a sentence describing time",
    "Generate a sentence with proper tense consistency",
    "Create a sentence using participles",
    "Make a sentence about relationships",
    "Generate a sentence with coordinating conjunctions",
    "Create a sentence about achievements",
    "Make a sentence with subordinating conjunctions",
    "Generate a sentence using metaphors",
    "Create a sentence about challenges",
    "Make a sentence with proper comma placement",
    "Generate a sentence using similes",
    "Create a sentence about innovation",
    "Make a sentence with varied punctuation",
    "Generate a sentence about exploration",
    "Create a sentence using noun phrases",
    "Make a sentence describing transitions",
    "Generate a sentence with complex syntax",
    "Create a sentence about discovery",
    "Make a sentence using adjective clauses",
    "Generate a sentence about growth",
    "Create a sentence with proper capitalization",
    "Make a sentence about transformation",
    "Generate a sentence using prepositional phrases",
    "Create a sentence about connections",
    "Make a sentence describing moments",
    "Generate a sentence with proper voice",
    "Create a sentence about experiences",
]
