QUESTIONS = [
    "Generate an image of a sunset over mountains",
    "Create a picture of a futuristic city",
    "Make an image of a cute cat wearing a hat",
    "Generate a logo for my coffee shop",
    "Create an illustration of a dragon",
    "Make an image of a peaceful garden",
    "Generate a portrait of a cyberpunk character",
    "Create a picture of an alien landscape",
    "Make an image of a vintage car",
    "Generate artwork in the style of Van Gogh",
    "Create an image of a magical forest",
    "Make a picture of a modern office space",
    "Generate an image of a steampunk airship",
    "Create a minimalist poster design",
    "Make an image of a tropical beach",
    "Generate a fantasy castle illustration",
    "Create a picture of a robot chef",
    "Make an image of northern lights",
    "Generate a book cover design",
    "Create an image of an underwater city",
    "Make a picture of a cozy cabin in winter",
    "Generate an abstract art piece",
    "Create an image of a superhero",
    "Make a picture of a Japanese garden",
    "Generate a product mockup",
    "Create an image of space exploration",
    "Make a picture of a medieval marketplace",
    "Generate a Halloween-themed illustration",
    "Create an image of a luxury yacht",
    "Make a picture of cherry blossoms",
    "Generate a company mascot design",
    "Create an image of a post-apocalyptic world",
    "Make a picture of a grand library",
    "Generate a wedding invitation design",
    "Create an image of mythical creatures",
    "Make a picture of a bustling city street",
    "Generate an isometric room illustration",
    "Create an image of a space station",
    "Make a picture of autumn leaves",
    "Generate a tattoo design",
    "Create an image of ancient ruins",
    "Make a picture of a fancy restaurant",
    "Generate a social media banner",
    "Create an image of floating islands",
    "Make a picture of a home gym",
    "Generate a children's book illustration",
    "Create an image of a thunderstorm",
    "Make a picture of a zen meditation room",
    "Generate a festival poster",
    "Create an image of bioluminescent creatures",
    "Make a picture of a rooftop garden",
    "Generate a mascot for a sports team",
    "Create an image of crystal caves",
    "Make a picture of a modern kitchen",
    "Generate an album cover design",
    "Create an image of samurai warrior",
    "Make a picture of desert dunes",
    "Generate a business card design",
    "Create an image of clockwork mechanisms",
    "Make a picture of a waterfall",
    "Generate a pattern for fabric",
    "Create an image of deep ocean creatures",
    "Make a picture of a treehouse",
    "Generate an infographic design",
    "Create an image of egyptian pyramids",
    "Make a picture of a yoga studio",
    "Generate a menu design for restaurant",
    "Create an image of fairy tale scene",
    "Make a picture of mountain climber",
    "Generate a app icon design",
    "Create an image of time travel portal",
    "Make a picture of english countryside",
    "Generate a thumbnail for YouTube",
    "Create an image of viking ship",
    "Make a picture of butterfly garden",
    "Generate a certificate design",
    "Create an image of coral reef",
    "Make a picture of home office setup",
    "Generate a t-shirt design",
    "Create an image of lunar base",
    "Make a picture of lavender fields",
    "Generate an image of a futuristic city",
    "Create an image of a serene ocean sunset",
    "Draw a portrait of a mysterious figure",
    "Generate an abstract colorful pattern",
    "Paint an image of a dense forest",
    "Create an image of a cosmic galaxy",
    "Generate a surreal dreamlike landscape",
    "Draw an image of ancient ruins",
    "Paint a portrait of a wise old mentor",
    "Create an image of a cyberpunk metropolis",
    "Generate an image of a peaceful meditation space",
    "Draw a mountain peak with snow",
    "Paint an image of underwater creatures",
    "Create an image of a magical crystal cave",
    "Generate an image of a futuristic robot",
    "Draw an image of a blooming garden",
    "Paint a portrait of a creative artist",
    "Create an image of a steampunk airship",
    "Generate an image of northern lights",
    "Draw an image of ancient temples",
    "Paint an image of a serene Zen garden",
    "Create an image of a neon-lit street",
    "Generate an image of a majestic eagle",
    "Draw an image of a futuristic spacecraft",
    "Paint an image of a peaceful river",
    "Create an image of a fantasy castle",
    "Generate an image of glowing particles",
    "Draw an image of a mechanical heart",
    "Paint an image of a blooming lotus",
    "Create an image of a digital circuit",
    "Generate an image of a desert oasis",
    "Draw an image of a phoenix rising",
    "Paint an image of a stormy sky",
    "Create an image of a bioluminescent forest",
    "Generate an image of a geometric mandala",
    "Draw an image of a technological interface",
    "Paint an image of an enchanted forest",
    "Create an image of a shimmering waterfall",
    "Generate an image of a time machine",
    "Draw an image of a celestial body",
    "Paint an image of a secret garden",
    "Create an image of a holographic display",
    "Generate an image of a volcanic landscape",
    "Draw an image of a mechanical butterfly",
    "Paint an image of a peaceful sunset",
    "Create an image of a quantum field",
    "Generate an image of a mystical portal",
    "Draw an image of a digital art piece",
    "Paint an image of a serene sanctuary",
    "Create an image of an alien world",
    "Generate an image of a futuristic city",
    "Create an image of a serene ocean sunset",
    "Draw a portrait of a mysterious figure",
    "Generate an abstract colorful pattern",
    "Paint an image of a dense forest",
    "Create an image of a cosmic galaxy",
    "Generate a surreal dreamlike landscape",
    "Draw an image of ancient ruins",
    "Paint a portrait of a wise old mentor",
    "Create an image of a cyberpunk metropolis",
    "Generate an image of a peaceful meditation space",
    "Draw a mountain peak with snow",
    "Paint an image of underwater creatures",
    "Create an image of a magical crystal cave",
    "Generate an image of a futuristic robot",
    "Draw an image of a blooming garden",
    "Paint a portrait of a creative artist",
    "Create an image of a steampunk airship",
    "Generate an image of northern lights",
    "Draw an image of ancient temples",
    "Paint an image of a serene Zen garden",
    "Create an image of a neon-lit street",
    "Generate an image of a majestic eagle",
    "Draw an image of a futuristic spacecraft",
    "Paint an image of a peaceful river",
    "Create an image of a fantasy castle",
    "Generate an image of glowing particles",
    "Draw an image of a mechanical heart",
    "Paint an image of a blooming lotus",
    "Create an image of a digital circuit",
    "Generate an image of a desert oasis",
    "Draw an image of a phoenix rising",
    "Paint an image of a stormy sky",
    "Create an image of a bioluminescent forest",
    "Generate an image of a geometric mandala",
    "Draw an image of a technological interface",
    "Paint an image of an enchanted forest",
    "Create an image of a shimmering waterfall",
    "Generate an image of a time machine",
    "Draw an image of a celestial body",
    "Paint an image of a secret garden",
    "Create an image of a holographic display",
    "Generate an image of a volcanic landscape",
    "Draw an image of a mechanical butterfly",
    "Paint an image of a peaceful sunset",
    "Create an image of a quantum field",
    "Generate an image of a mystical portal",
    "Draw an image of a digital art piece",
    "Paint an image of a serene sanctuary",
    "Create an image of an alien world",
]
