QUESTIONS = [
    "learn Python is a great language",
    "learn The Earth orbits the Sun",
    "learn Machine learning is powerful",
    "learn backpropagation computes gradients",
    "learn the sky is blue",
    "learn neural networks learn patterns",
    "learn water freezes at 0 degrees Celsius",
    "learn quantum physics is fascinating",
    "learn the speed of light is 299792458 m/s",
    "remember this fact",
    "note that the moon orbits Earth",
    "memorize pi equals 3.14159",
    "store this knowledge",
    "save this information",
    "remember that DNA is a double helix",
    "learn that Python was created by Guido van Rossum",
    "remember the sun is 93 million miles away",
    "note that chess has more positions than atoms",
    "learn gradient descent minimizes the loss function",
    "store the definition of entropy",
    "learn transformers use attention mechanisms",
    "remember that the Amazon rainforest covers 2.1 million square miles",
    "learn the periodic table has 118 elements",
    "remember that c is approximately 299792458 m/s",
    "learn the capital of France is Paris",
    "store that the Earth is 4.54 billion years old",
    "memorize that the human body has 206 bones",
    "note that the Great Wall of China is 21,196 km long",
    "learn that the Eiffel Tower is 330 meters tall",
    "remember the hottest planet is Venus",
    "Remember that Python is a versatile programming language",
    "Learn that machine learning helps computers learn from data",
    "Store the fact that AI is transforming industries",
    "Note that quantum computing is emerging",
    "Memorize that neural networks mimic brain functions",
    "Learn that deep learning uses multiple layers",
    "Remember that transformers revolutionized NLP",
    "Store the fact that ethics in AI is crucial",
    "Note that big data requires advanced processing",
    "Memorize that algorithms are step-by-step procedures",
    "Learn that APIs enable software communication",
    "Remember that databases organize information",
    "Store the fact that cybersecurity protects systems",
    "Note that cloud computing offers scalability",
    "Memorize that blockchain ensures transparency",
    "Learn that IoT connects physical devices",
    "Remember that edge computing reduces latency",
    "Store the fact that 5G enables fast connectivity",
    "Note that augmented reality enhances experiences",
    "Memorize that virtual reality creates immersion",
    "Learn that natural language processing understands text",
    "Remember that computer vision interprets images",
    "Store the fact that robotics automates tasks",
    "Note that biometrics provide security",
    "Memorize that sustainability is important for technology",
    "Learn that open source promotes collaboration",
    "Remember that data privacy is essential",
    "Store the fact that encryption secures information",
    "Note that artificial general intelligence is aspirational",
    "Memorize that human-AI collaboration is powerful",
    "Learn that Moore's law describes computing trends",
    "Remember that version control manages code changes",
    "Store the fact that testing ensures quality",
    "Note that documentation explains systems",
    "Memorize that user experience matters greatly",
    "Learn that DevOps integrates development and operations",
    "Remember that containers enable portability",
    "Store the fact that microservices improve flexibility",
    "Note that serverless computing reduces overhead",
    "Memorize that monitoring detects issues early",
    "Learn that logging provides insights",
    "Remember that caching improves performance",
    "Store the fact that load balancing distributes traffic",
    "Note that encryption protects communications",
    "Memorize that authentication verifies identity",
    "Learn that authorization controls access",
    "Remember that backups prevent data loss",
    "Store the fact that disaster recovery ensures continuity",
    "Note that compliance standards guide practices",
    "Memorize that innovation drives progress",
    "Remember that Python is a versatile programming language",
    "Learn that machine learning helps computers learn from data",
    "Store the fact that AI is transforming industries",
    "Note that quantum computing is emerging",
    "Memorize that neural networks mimic brain functions",
    "Learn that deep learning uses multiple layers",
    "Remember that transformers revolutionized NLP",
    "Store the fact that ethics in AI is crucial",
    "Note that big data requires advanced processing",
    "Memorize that algorithms are step-by-step procedures",
    "Learn that APIs enable software communication",
    "Remember that databases organize information",
    "Store the fact that cybersecurity protects systems",
    "Note that cloud computing offers scalability",
    "Memorize that blockchain ensures transparency",
    "Learn that IoT connects physical devices",
    "Remember that edge computing reduces latency",
    "Store the fact that 5G enables fast connectivity",
    "Note that augmented reality enhances experiences",
    "Memorize that virtual reality creates immersion",
    "Learn that natural language processing understands text",
    "Remember that computer vision interprets images",
    "Store the fact that robotics automates tasks",
    "Note that biometrics provide security",
    "Memorize that sustainability is important for technology",
    "Learn that open source promotes collaboration",
    "Remember that data privacy is essential",
    "Store the fact that encryption secures information",
    "Note that artificial general intelligence is aspirational",
    "Memorize that human-AI collaboration is powerful",
    "Learn that Moore's law describes computing trends",
    "Remember that version control manages code changes",
    "Store the fact that testing ensures quality",
    "Note that documentation explains systems",
    "Memorize that user experience matters greatly",
    "Learn that DevOps integrates development and operations",
    "Remember that containers enable portability",
    "Store the fact that microservices improve flexibility",
    "Note that serverless computing reduces overhead",
    "Memorize that monitoring detects issues early",
    "Learn that logging provides insights",
    "Remember that caching improves performance",
    "Store the fact that load balancing distributes traffic",
    "Note that encryption protects communications",
    "Memorize that authentication verifies identity",
    "Learn that authorization controls access",
    "Remember that backups prevent data loss",
    "Store the fact that disaster recovery ensures continuity",
    "Note that compliance standards guide practices",
    "Memorize that innovation drives progress",
]
