QUESTIONS = [
    "predict artificial intelligence",
    "predict hello world confidence",
    "predict quantum computing",
    "show intent probabilities",
    "classify this sentence",
    "what is the intent here",
    "show me the moe prediction",
    "intent prediction for this",
    "predict label",
    "show model output",
    "run inference on this",
    "predict the category",
    "what intent would you predict for this",
    "show prediction confidence",
    "classify my input",
    "what does the model say about this",
    "show me the probability distribution",
    "what is the top predicted intent",
    "run the classifier on this text",
    "show inference results",
    "predict and explain the classification",
    "what category is this query",
    "show all intent scores",
    "predict intent: hello I want to search",
    "classify this as an intent",
    "run prediction on my input",
    "what does the neural network predict",
    "show the MoE expert activation",
    "display expert load for this query",
    "show which experts were activated",
    "Predict the next number in the sequence",
    "Classify this text into categories",
    "What is the sentiment of this review?",
    "Predict customer churn probability",
    "Classify images as cat or dog",
    "Predict house prices given features",
    "Classify emails as spam or not spam",
    "Predict stock price movement",
    "Classify sentiment as positive, negative, or neutral",
    "Predict customer lifetime value",
    "Classify news articles by topic",
    "Predict disease probability from symptoms",
    "Classify movie reviews by rating",
    "Predict sales for next quarter",
    "Classify weather patterns",
    "Predict user behavior",
    "Classify documents by language",
    "Predict network traffic",
    "Classify anomalies in data",
    "Predict equipment failure",
    "Classify transactions as fraudulent",
    "Predict student performance",
    "Classify flowers by species",
    "Predict hiring success",
    "Classify credit risk levels",
    "Predict attrition rates",
    "Classify page content",
    "Predict demand forecasting",
    "Classify text as offensive or clean",
    "Predict loan approval likelihood",
    "Classify articles by credibility",
    "Predict energy consumption",
    "Classify images by quality",
    "Predict customer satisfaction",
    "Classify network packets",
    "Predict cryptocurrency trends",
    "Classify user demographics",
    "Predict system failures",
    "Classify documents for compliance",
    "Predict user retention",
    "Classify feedback urgency",
    "Predict optimization outcomes",
    "Classify data quality issues",
    "Predict recovery time",
    "Classify security threats",
    "Predict conversion rates",
    "Classify social media sentiment",
    "Predict: Given input features, classify output category",
    "What is the probability of this event occurring?",
    "Classify: Determine which class this belongs to",
    "Predict the trend based on historical data",
    "Classify this data point into predefined categories",
    "What is the likelihood of success?",
    "Predict future values based on patterns",
    "Classify text into sentiment categories",
    "What category does this fall under?",
    "Predict the outcome of this scenario",
    "Classify images by their content",
    "What is the predicted probability?",
    "Determine the class label for this instance",
    "Predict based on learned patterns",
    "Classify records by similarity",
    "What outcome is most likely?",
    "Predict customer behavior from past data",
    "Classify documents by relevance",
    "What prediction do the features indicate?",
    "Determine probability distribution over classes",
    "Predict time series progression",
    "Classify based on decision boundaries",
    "What does the model predict?",
    "Predict regression value from inputs",
    "Classify using probabilistic methods",
    "What is the confidence score?",
    "Predict using trained neural network",
    "Classify with decision tree logic",
    "What category is most probable?",
    "Predict outcomes from feature vectors",
    "Classify sequences using RNN",
    "What probability threshold applies?",
    "Predict using ensemble methods",
    "Classify with clustering results",
    "What inference does data suggest?",
    "Predict using Bayesian approach",
    "Classify with SVM decision boundary",
    "What categorical prediction results?",
    "Predict using polynomial regression",
    "Classify with k-nearest neighbors",
    "What is the predicted class?",
    "Predict using linear discriminant",
    "Classify using naive Bayes",
    "What probability is highest?",
    "Predict outcomes from embeddings",
    "Classify with random forest",
    "What does cross-validation predict?",
    "Predict using transfer learning",
    "Classify with attention mechanism",
    "Predict resource requirements",
    "Predict the next number in the sequence",
    "Classify this text into categories",
    "What is the sentiment of this review?",
    "Predict customer churn probability",
    "Classify images as cat or dog",
    "Predict house prices given features",
    "Classify emails as spam or not spam",
    "Predict stock price movement",
    "Classify sentiment as positive, negative, or neutral",
    "Predict customer lifetime value",
    "Classify news articles by topic",
    "Predict disease probability from symptoms",
    "Classify movie reviews by rating",
    "Predict sales for next quarter",
    "Classify weather patterns",
    "Predict user behavior",
    "Classify documents by language",
    "Predict network traffic",
    "Classify anomalies in data",
    "Predict equipment failure",
    "Classify transactions as fraudulent",
    "Predict student performance",
    "Classify flowers by species",
    "Predict hiring success",
    "Classify credit risk levels",
    "Predict attrition rates",
    "Classify page content",
    "Predict demand forecasting",
    "Classify text as offensive or clean",
    "Predict loan approval likelihood",
    "Classify articles by credibility",
    "Predict energy consumption",
    "Classify images by quality",
    "Predict customer satisfaction",
    "Classify network packets",
    "Predict cryptocurrency trends",
    "Classify user demographics",
    "Predict system failures",
    "Classify documents for compliance",
    "Predict user retention",
    "Classify feedback urgency",
    "Predict optimization outcomes",
    "Classify data quality issues",
    "Predict recovery time",
    "Classify security threats",
    "Predict conversion rates",
    "Classify social media sentiment",
    "Predict resource requirements",
    "Classify priority levels",
    "Predict team productivity",
]
