QUESTIONS = [
    "Based on the document I uploaded, what are the key findings?",
    "Search through the files and find information about revenue",
    "What does the manual say about installation?",
    "Find references to climate change in these articles",
    "According to the research paper, what was the methodology?",
    "Search the knowledge base for troubleshooting steps",
    "What information is in the contract about termination?",
    "Find all mentions of security in the documentation",
    "Based on the meeting notes, what were the action items?",
    "Search the database for customer complaints",
    "What does the policy document say about refunds?",
    "Find information about side effects in the medical literature",
    "According to these reports, what are the trends?",
    "Search through the emails for project updates",
    "What does the user guide say about configuration?",
    "Find evidence in the documents supporting this claim",
    "Based on the financial statements, what is the profit margin?",
    "Search the archives for historical data",
    "What information exists about this topic in our documents?",
    "Find all relevant passages about machine learning",
    "According to the specification document, what are requirements?",
    "Search through the legal documents for precedents",
    "What does the research say about effectiveness?",
    "Find quotes from the interview transcripts",
    "Based on the case studies, what are best practices?",
    "Search the knowledge base for similar issues",
    "What information is available about pricing?",
    "Find references to this author in the bibliography",
    "According to the safety guidelines, what precautions are needed?",
    "Search through product reviews for common complaints",
    "What does the employee handbook say about vacation?",
    "Find statistical data in the research papers",
    "Based on customer feedback, what are main concerns?",
    "Search the documentation for API endpoints",
    "What information exists about competitors?",
    "Find all instances of this keyword in the corpus",
    "According to the audit report, what were the findings?",
    "Search through the invoices for discrepancies",
    "What does the literature review reveal about this topic?",
    "Find supporting evidence from the sources",
    "Based on the survey results, what do users want?",
    "Search the manual for error codes",
    "What information is in the white paper about methodology?",
    "Find mentions of sustainability in corporate reports",
    "According to the terms of service, what are limitations?",
    "Search through the logs for error patterns",
    "What does the technical documentation say about compatibility?",
    "Find relevant case law in the legal database",
    "Based on the article, what are the main arguments?",
    "Search the repository for code examples",
    "What information exists about adverse events?",
    "Find all citations of this study",
    "According to the minutes, what was decided?",
    "Search through the testimonials for positive feedback",
    "What does the compliance document require?",
    "Find data points supporting this hypothesis",
    "Based on the transcript, what were key points?",
    "Search the FAQ for answers about shipping",
    "What information is available about ingredients?",
    "Find references to this concept in the textbook",
    "According to the evaluation, what are strengths?",
    "Search through the correspondence for agreements",
    "What does the clinical trial data show?",
    "Find examples in the documentation",
    "Based on the analysis, what are recommendations?",
    "Search the catalog for product specifications",
    "What information exists about patent applications?",
    "Find mentions of risks in the disclosure documents",
    "According to the guidelines, what is the process?",
    "Search through the publications for citations",
    "What does the environmental report say about impact?",
    "Find relevant passages about ethics",
    "Based on the data, what are correlations?",
    "Search the records for transaction history",
    "What information is in the prospectus about returns?",
    "Find all sections about privacy in the policy",
    "According to the study, what were limitations?",
    "Search through the content for specific examples",
    "What does the documentation say about dependencies?",
    "Find comparative data in the benchmarking report",
    "RAG: What are the latest breakthroughs in quantum computing?",
    "Retrieve and generate about renewable energy sources",
    "RAG search for information on sustainable farming",
    "Using knowledge base, explain blockchain technology",
    "RAG about the history of artificial intelligence",
    "Retrieve and generate about climate change solutions",
    "RAG search for COVID-19 research findings",
    "Using knowledge base, explain genetic engineering",
    "RAG about advanced materials and nanotechnology",
    "Retrieve and generate about space exploration missions",
    "RAG search for cybersecurity best practices",
    "Using knowledge base, explain neuroscience discoveries",
    "RAG about biotechnology applications",
    "Retrieve and generate about ocean conservation",
    "RAG search for renewable battery technologies",
    "Using knowledge base, explain synthetic biology",
    "RAG about pandemic preparedness",
    "Retrieve and generate about cancer research",
    "RAG search for mental health resources",
    "Using knowledge base, explain personalized medicine",
    "RAG about wildlife conservation efforts",
    "Retrieve and generate about poverty reduction strategies",
    "RAG search for education innovation models",
    "Using knowledge base, explain ethical AI development",
    "RAG about space station research",
    "Retrieve and generate about water purification methods",
    "RAG search for agriculture technology",
    "Using knowledge base, explain gravity waves",
    "RAG about human microbiome research",
    "Retrieve and generate about archaeological discoveries",
    "RAG search for language preservation",
    "Using knowledge base, explain gene therapy",
    "RAG about atmospheric science",
    "Retrieve and generate about cultural heritage protection",
    "RAG search for materials science breakthroughs",
    "Using knowledge base, explain immunotherapy",
    "RAG about polar research expeditions",
    "Retrieve and generate about digital preservation",
    "RAG search for soil science discoveries",
    "Using knowledge base, explain exoplanet research",
    "RAG about biodiversity mapping",
    "Retrieve and generate about conservation technology",
    "RAG search for renewable hydrogen production",
    "Using knowledge base, explain evolutionary biology",
    "RAG about environmental monitoring systems",
    "Retrieve and generate about ecosystem restoration",
    "RAG search for clean cooking technologies",
    "Using knowledge base, explain protein folding",
    "RAG about geological discoveries",
    "RAG: What are the latest breakthroughs in quantum computing?",
    "Retrieve and generate about renewable energy sources",
    "RAG search for information on sustainable farming",
    "Using knowledge base, explain blockchain technology",
    "RAG about the history of artificial intelligence",
    "Retrieve and generate about climate change solutions",
    "RAG search for COVID-19 research findings",
    "Using knowledge base, explain genetic engineering",
    "RAG about advanced materials and nanotechnology",
    "Retrieve and generate about space exploration missions",
    "RAG search for cybersecurity best practices",
    "Using knowledge base, explain neuroscience discoveries",
    "RAG about biotechnology applications",
    "Retrieve and generate about ocean conservation",
    "RAG search for renewable battery technologies",
    "Using knowledge base, explain synthetic biology",
    "RAG about pandemic preparedness",
    "Retrieve and generate about cancer research",
    "RAG search for mental health resources",
    "Using knowledge base, explain personalized medicine",
    "RAG about wildlife conservation efforts",
    "Retrieve and generate about poverty reduction strategies",
    "RAG search for education innovation models",
    "Using knowledge base, explain ethical AI development",
    "RAG about space station research",
    "Retrieve and generate about water purification methods",
    "RAG search for agriculture technology",
    "Using knowledge base, explain gravity waves",
    "RAG about human microbiome research",
    "Retrieve and generate about archaeological discoveries",
    "RAG search for language preservation",
    "Using knowledge base, explain gene therapy",
    "RAG about atmospheric science",
    "Retrieve and generate about cultural heritage protection",
    "RAG search for materials science breakthroughs",
    "Using knowledge base, explain immunotherapy",
    "RAG about polar research expeditions",
    "Retrieve and generate about digital preservation",
    "RAG search for soil science discoveries",
    "Using knowledge base, explain exoplanet research",
    "RAG about biodiversity mapping",
    "Retrieve and generate about conservation technology",
    "RAG search for renewable hydrogen production",
    "Using knowledge base, explain evolutionary biology",
    "RAG about environmental monitoring systems",
    "Retrieve and generate about ecosystem restoration",
    "RAG search for clean cooking technologies",
    "Using knowledge base, explain protein folding",
    "RAG about geological discoveries",
    "Retrieve and generate about climate science",
]
