TRAINING_DATA = [
    {"question": "Search for the best restaurants near me", "think": "<think>User wants local restaurants. Need to: 1) Identify location context, 2) Consider proximity as key factor, 3) Search for ratings/reviews for quality</think>"},
    {"question": "Find information about climate change", "think": "<think>This is a complex topic. Need to: 1) Gather scientific data, 2) Understand multiple perspectives, 3) Look for credible sources, 4) Consider causes and effects</think>"},
    {"question": "Look up the weather in New York", "think": "<think>Need real-time data. Steps: 1) Identify location (New York), 2) Fetch current conditions, 3) Gather forecast info, 4) Present clearly</think>"},
    {"question": "Search for Python tutorials", "think": "<think>User wants to learn. Consider: 1) Beginner vs advanced, 2) Different formats (video, text, interactive), 3) Quality and relevance, 4) Structured learning paths</think>"},
    {"question": "Find the latest news on AI", "think": "<think>Need current information. Steps: 1) Query recent sources, 2) Filter by relevance, 3) Prioritize latest updates, 4) Identify key developments</think>"},
    {"question": "Look up symptoms of flu", "think": "<think>Medical information. Need to: 1) List common symptoms, 2) Distinguish from other illnesses, 3) Provide when to seek help, 4) Suggest preventative measures</think>"},
    {"question": "Search for flights to Paris", "think": "<think>Travel query. Consider: 1) Departure location/dates, 2) Price comparison, 3) Available carriers, 4) Travel dates flexibility</think>"},
    {"question": "Find hotels in Tokyo", "think": "<think>Travel planning. Need: 1) Location preferences, 2) Budget range, 3) Amenities/ratings, 4) Proximity to attractions</think>"},
    {"question": "Look up the definition of ephemeral", "think": "<think>Vocabulary lookup. Need to: 1) Provide precise definition, 2) Give etymology, 3) Show usage examples, 4) List synonyms</think>"},
    {"question": "Search for chocolate chip cookie recipes", "think": "<think>Recipe search. Consider: 1) Difficulty level, 2) Ingredient availability, 3) Baking time, 4) Variations (chewy, crispy, etc)</think>"},
    {"question": "Find reviews of iPhone 15", "think": "<think>Product review. Analyze: 1) User ratings, 2) Key features, 3) Pros/cons, 4) Compare to competitors, 5) Price point</think>"},
    {"question": "Look up movie times for Dune", "think": "<think>Entertainment query. Need: 1) Location/theater, 2) Available showtimes, 3) Format options (IMAX, subtitles), 4) Ticket availability</think>"},
    {"question": "Search for jobs in software engineering", "think": "<think>Job search. Consider: 1) Experience level, 2) Location/remote options, 3) Tech stack, 4) Salary range, 5) Company culture</think>"},
    {"question": "Find the best laptop under $1000", "think": "<think>Product comparison. Evaluate: 1) Specifications (CPU, RAM, storage), 2) Performance benchmarks, 3) User reviews, 4) Warranty/support</think>"},
    {"question": "Look up how to tie a tie", "think": "<think>How-to guide. Need: 1) Step-by-step instructions, 2) Visual aids, 3) Different knot types, 4) Common mistakes to avoid</think>"},
    {"question": "Search for yoga classes nearby", "think": "<think>Local services. Check: 1) Class types, 2) Schedule/availability, 3) Instructor qualifications, 4) Reviews and prices</think>"},
    {"question": "Find statistics on population growth", "think": "<think>Data research. Need: 1) Reliable sources, 2) Time period context, 3) Regional breakdowns, 4) Growth rate analysis</think>"},
    {"question": "Look up the history of the Roman Empire", "think": "<think>Historical inquiry. Cover: 1) Timeline and key periods, 2) Major figures, 3) Political/military events, 4) Cultural impact</think>"},
    {"question": "Search for electric cars comparison", "think": "<think>Comparison task. Analyze: 1) Models and specifications, 2) Price comparison, 3) Range and charging, 4) Environmental benefits</think>"},
    {"question": "Find documentaries about space", "think": "<think>Content discovery. Consider: 1) Topic (planets, galaxies, astronauts), 2) Source (streaming platforms), 3) Reviews, 4) Length and depth</think>"},
    {"question": "Look up healthy breakfast ideas", "think": "<think>Lifestyle advice. Think: 1) Nutritional balance, 2) Time to prepare, 3) Ingredients availability, 4) Dietary restrictions</think>"},
    {"question": "Search for scientific papers on quantum computing", "think": "<think>Academic search. Need: 1) Peer-reviewed sources, 2) Relevance to topic, 3) Publication date, 4) Citation counts</think>"},
    {"question": "Find the nearest coffee shop", "think": "<think>Location query. Steps: 1) Get current location, 2) Search nearby, 3) Filter by distance, 4) Check hours/ratings</think>"},
    {"question": "Look up travel tips for Japan", "think": "<think>Travel planning. Consider: 1) Transportation options, 2) Cultural etiquette, 3) Language barriers, 4) Budget and accommodations</think>"},
    {"question": "Search for beginner guitar lessons", "think": "<think>Learning resource. Evaluate: 1) Instructor level, 2) Format (online/in-person), 3) Lesson structure, 4) Cost and flexibility</think>"},
    {"question": "Find the best running shoes for marathon", "think": "<think>Athletic gear. Analyze: 1) Running style, 2) Cushioning needs, 3) Durability for distance, 4) Professional reviews</think>"},
    {"question": "Look up stock market trends", "think": "<think>Financial data. Examine: 1) Market performance, 2) Sector analysis, 3) Economic indicators, 4) Expert predictions</think>"},
    {"question": "Search for vegan restaurants in LA", "think": "<think>Restaurant search. Filter: 1) Cuisine type, 2) Location in LA, 3) Reviews and ratings, 4) Price range and menus</think>"},
    {"question": "Find information about the Apollo missions", "think": "<think>Historical research. Cover: 1) Mission timeline, 2) Astronauts involved, 3) Achievements and discoveries, 4) Impact on space exploration</think>"},
    {"question": "Look up meditation techniques", "think": "<think>Wellness guide. Explore: 1) Different meditation types, 2) Skill level required, 3) Benefits for beginners, 4) Resources for practice</think>"},
    {"question": "Search for home workout routines", "think": "<think>Fitness advice. Consider: 1) Fitness level, 2) Available space, 3) Equipment needed, 4) Time commitment</think>"},
    {"question": "Find scholarships for engineering students", "think": "<think>Education search. Research: 1) Eligibility criteria, 2) Funding amounts, 3) Application deadlines, 4) GPA requirements</think>"},
    {"question": "Look up the best universities for computer science", "think": "<think>Educational ranking. Evaluate: 1) Rankings, 2) Program strengths, 3) Location preferences, 4) Tuition costs</think>"},
    {"question": "Search for DIY home improvement projects", "think": "<think>Project planning. Think: 1) Skill level needed, 2) Materials required, 3) Time and cost estimates, 4) Difficulty and feasibility</think>"},
    {"question": "Find the meaning of life", "think": "<think>Philosophical inquiry. Explore: 1) Different philosophical perspectives, 2) Religious viewpoints, 3) Personal meaning, 4) Purpose and fulfillment</think>"},
    {"question": "Look up tax filing deadlines", "think": "<think>Administrative info. Need: 1) Relevant deadlines, 2) Filing requirements, 3) Extension options, 4) Important dates</think>"},
    {"question": "Search for affordable health insurance", "think": "<think>Insurance search. Compare: 1) Plan types and coverage, 2) Premium costs, 3) Deductibles, 4) Provider networks</think>"},
    {"question": "Find pet adoption centers nearby", "think": "<think>Community services. Check: 1) Available animals, 2) Location and hours, 3) Adoption process, 4) Support services</think>"},
    {"question": "Look up tips for better sleep", "think": "<think>Health advice. Consider: 1) Sleep hygiene practices, 2) Environmental factors, 3) Dietary effects, 4) Stress management</think>"},
    {"question": "Search for sustainable fashion brands", "think": "<think>Consumer research. Evaluate: 1) Sustainability practices, 2) Ethical sourcing, 3) Product quality, 4) Price point and availability</think>"},
    {"question": "Find the best VPN services", "think": "<think>Tech tool evaluation. Compare: 1) Security features, 2) Speed and reliability, 3) Price, 4) Privacy policies</think>"},
    {"question": "Look up how photosynthesis works", "think": "<think>Scientific explanation. Cover: 1) Basic mechanism, 2) Chemical process, 3) Role of chlorophyll, 4) Environmental importance</think>"},
    {"question": "Search for mental health resources", "think": "<think>Support services. Find: 1) Counseling/therapy options, 2) Crisis hotlines, 3) Support groups, 4) Online resources</think>"},
    {"question": "Find camping sites in California", "think": "<think>Travel planning. Consider: 1) Location preferences, 2) Amenities available, 3) Difficulty level, 4) Seasonal availability</think>"},
    {"question": "Look up the best books of 2023", "think": "<think>Literature research. Explore: 1) Genre preferences, 2) Critical reviews, 3) Reader ratings, 4) Award winners</think>"},
    {"question": "Search for coding bootcamps online", "think": "<think>Education research. Evaluate: 1) Curriculum quality, 2) Job placement rates, 3) Cost and duration, 4) Student reviews</think>"},
    {"question": "Find data on renewable energy", "think": "<think>Environmental research. Gather: 1) Energy sources, 2) Statistics and trends, 3) Implementation challenges, 4) Future potential</think>"},
    {"question": "Look up interview tips for tech jobs", "think": "<think>Career advice. Include: 1) Technical preparation, 2) Behavioral interview strategies, 3) Company research, 4) Follow-up tactics</think>"},
    {"question": "Search for car insurance quotes", "think": "<think>Consumer comparison. Analyze: 1) Coverage types, 2) Premium costs, 3) Deductible options, 4) Discounts available</think>"},
]

# Keep QUESTIONS for backward compatibility
QUESTIONS = [q["question"] for q in TRAINING_DATA]
    "Search for drone technology applications",
    "Find research on immunotherapy treatments",
    "Look up nuclear fusion energy",
    "Search for water desalination methods",
    "Find information about vertical farming",
    "Look up blockchain applications",
    "Search for augmented reality development",
    "Find research on plastic alternatives",
    "Look up earthquake prediction methods",
    "Search for biodiversity conservation",
    "Find information about synthetic biology",
    "Look up carbon capture technology",
    "Search for gene editing techniques",
    "Find research on mental health treatment",
    "Look up robotics automation advances",
    "Search for space debris mitigation",
    "Find information about smart cities",
    "Look up antibiotic resistance research",
    "Search for forest restoration projects",
    "Find information about neural networks",
    "Look up earthquake early warning systems",
    "Search for wildlife migration patterns",
    "Find research on particle physics",
    "Look up deep sea exploration",
    "Search for meteorite impacts",
    "Find information about polymer science",
    "Look up epidemiology modeling",
    "Search for renewable agriculture",
    "Find research on computational biology",
    "Look up architectural innovations",
    "Search for paleontology discoveries",
    "Search for information on artificial intelligence applications",
    "Find the latest research on quantum computing",
    "Look up renewable energy storage solutions",
    "Search for space exploration missions",
    "Find information about genetic engineering",
    "Look up climate change mitigation strategies",
    "Search for nanotechnology applications",
    "Find research on brain-computer interfaces",
    "Look up sustainable agriculture practices",
    "Search for cancer treatment breakthroughs",
    "Find information about biometric authentication",
    "Look up cybersecurity threat prevention",
    "Search for autonomous vehicle development",
    "Find research on alzheimer's disease",
    "Look up 5G network infrastructure",
    "Search for ocean acidification solutions",
    "Find information about precision medicine",
    "Look up battery technology innovations",
    "Search for drone technology applications",
    "Find research on immunotherapy treatments",
    "Look up nuclear fusion energy",
    "Search for water desalination methods",
    "Find information about vertical farming",
    "Look up blockchain applications",
    "Search for augmented reality development",
    "Find research on plastic alternatives",
    "Look up earthquake prediction methods",
    "Search for biodiversity conservation",
    "Find information about synthetic biology",
    "Look up carbon capture technology",
    "Search for gene editing techniques",
    "Find research on mental health treatment",
    "Look up robotics automation advances",
    "Search for space debris mitigation",
    "Find information about smart cities",
    "Look up antibiotic resistance research",
    "Search for forest restoration projects",
    "Find information about neural networks",
    "Look up earthquake early warning systems",
    "Search for wildlife migration patterns",
    "Find research on particle physics",
    "Look up deep sea exploration",
    "Search for meteorite impacts",
    "Find information about polymer science",
    "Look up epidemiology modeling",
    "Search for renewable agriculture",
    "Find research on computational biology",
    "Look up architectural innovations",
    "Search for paleontology discoveries",
    "Find information about materials science",
]
