QUESTIONS = [
    "Who are you?",
    "Who is Albert Einstein?",
    "Who was the first president of the United States?",
    "Who invented the telephone?",
    "Who created you?",
    "Who is the CEO of Tesla?",
    "Who wrote Romeo and Juliet?",
    "Who is Marie Curie?",
    "Who won the World Cup in 2022?",
    "Who discovered penicillin?",
    "Who is the current president of France?",
    "Who painted the Mona Lisa?",
    "Who developed the theory of relativity?",
    "Who is Elon Musk?",
    "Who founded Microsoft?",
    "Who was Martin Luther King Jr?",
    "Who is the lead singer of Queen?",
    "Who directed The Godfather?",
    "Who wrote Harry Potter?",
    "Who is the protagonist in Breaking Bad?",
    "Who discovered America?",
    "Who invented the light bulb?",
    "Who is Taylor Swift?",
    "Who was Napoleon Bonaparte?",
    "Who is the founder of Amazon?",
    "Who wrote 1984?",
    "Who composed Beethoven's 5th Symphony?",
    "Who is the current Pope?",
    "Who was Cleopatra?",
    "Who invented the airplane?",
    "Who is Cristiano Ronaldo?",
    "Who founded Apple?",
    "Who was Shakespeare?",
    "Who is the Prime Minister of the UK?",
    "Who discovered gravity?",
    "Who is Oprah Winfrey?",
    "Who was Julius Caesar?",
    "Who created Facebook?",
    "Who is Beyoncé?",
    "Who won the Nobel Peace Prize in 2020?",
    "Who is the author of The Great Gatsby?",
    "Who was Alexander the Great?",
    "Who is Serena Williams?",
    "Who invented the computer?",
    "Who is the creator of Star Wars?",
    "Who was Nikola Tesla?",
    "Who is LeBron James?",
    "Who painted The Starry Night?",
    "Who is the voice of Darth Vader?",
    "Who was Queen Victoria?",
    "Who is Jeff Bezos?",
    "Who wrote The Catcher in the Rye?",
    "Who discovered DNA structure?",
    "Who is Barack Obama?",
    "Who was Leonardo da Vinci?",
    "Who is the strongest Avenger?",
    "Who was Mahatma Gandhi?",
    "Who is Lionel Messi?",
    "Who invented the printing press?",
    "Who is the author of Pride and Prejudice?",
    "Who was Thomas Edison?",
    "Who is Rihanna?",
    "Who founded Google?",
    "Who was Abraham Lincoln?",
    "Who is the director of Inception?",
    "Who was Winston Churchill?",
    "Who is Stephen Hawking?",
    "Who wrote To Kill a Mockingbird?",
    "Who was Socrates?",
    "Who is Bill Gates?",
    "Who was Rosa Parks?",
    "Who is the fastest man alive?",
    "Who invented the internet?",
    "Who is J.K. Rowling?",
    "Who was Aristotle?",
    "Who is the richest person in the world?",
    "Who was Charles Darwin?",
    "Who is Michael Jordan?",
    "Who wrote The Odyssey?",
    "Who was Isaac Newton?",
    "Who is Albert Einstein?",
    "Tell me about Marie Curie's achievements",
    "Who was Nikola Tesla?",
    "Describe Stephen Hawking's contributions",
    "Who is Elon Musk?",
    "Tell me about Billie Gates' philanthropy",
    "Who was Isaac Newton?",
    "Describe Alan Turing's legacy",
    "Who is Sundar Pichai?",
    "Tell me about Rosalind Franklin's work",
    "Who was Charles Darwin?",
    "Describe Richard Feynman's approach to science",
    "Who is Yann LeCun?",
    "Tell me about Joan Clarke's contributions",
    "Who was Galileo Galilei?",
    "Describe Carl Sagan's passion for science",
    "Who is Demis Hassabis?",
    "Tell me about Hedy Lamarr's innovations",
    "Who was Johannes Kepler?",
    "Describe Richard Stallman's open source philosophy",
    "Who is Bengio Yoshua?",
    "Tell me about Grace Hopper's programming legacy",
    "Who was James Clerk Maxwell?",
    "Describe Linus Torvalds' Linux creation",
    "Who is Andrew Ng?",
    "Tell me about Lovelace Ada's computing vision",
    "Who was Niels Bohr?",
    "Describe Guido van Rossum's Python language",
    "Who is Fei-Fei Li?",
    "Tell me about Margaret Hamilton's Apollo role",
    "Who was Erwin Schrodinger?",
    "Describe Dennis Ritchie's C programming language",
    "Who is Geoffrey Hinton?",
    "Tell me about Karen Sparck Jones' IR contributions",
    "Who was Richard Feynman?",
    "Describe Douglas Crockford's JavaScript work",
    "Who is Yoshua Bengio?",
    "Tell me about Hedy Lamarr's frequency hopping",
    "Who was Max Born?",
    "Describe Jeremy Howard's deep learning education",
    "Who is Hinton Geoffrey?",
    "Tell me about Radia Perlman's networking",
    "Who was Werner Heisenberg?",
    "Describe Rachel Thomas' AI fairness work",
    "Who is LeCun Yann?",
    "Tell me about Barbara Liskov's programming principles",
    "Who was Paul Dirac?",
    "Describe Timnit Gebru's AI ethics advocacy",
    "Who is Albert Einstein?",
    "Tell me about Marie Curie's achievements",
    "Who was Nikola Tesla?",
    "Describe Stephen Hawking's contributions",
    "Who is Elon Musk?",
    "Tell me about Bill Gates' philanthropy",
    "Who was Isaac Newton?",
    "Describe Alan Turing's legacy",
    "Who is Sundar Pichai?",
    "Tell me about Rosalind Franklin's work",
    "Who was Charles Darwin?",
    "Describe Richard Feynman's approach to science",
    "Who is Yann LeCun?",
    "Tell me about Joan Clarke's contributions",
    "Who was Galileo Galilei?",
    "Describe Carl Sagan's passion for science",
    "Who is Demis Hassabis?",
    "Tell me about Hedy Lamarr's innovations",
    "Who was Johannes Kepler?",
    "Describe Richard Stallman's open source philosophy",
    "Who is Bengio Yoshua?",
    "Tell me about Grace Hopper's programming legacy",
    "Who was James Clerk Maxwell?",
    "Describe Linus Torvalds' Linux creation",
    "Who is Andrew Ng?",
    "Tell me about Ada Lovelace's computing vision",
    "Who was Niels Bohr?",
    "Describe Guido van Rossum's Python language",
    "Who is Fei-Fei Li?",
    "Tell me about Margaret Hamilton's Apollo role",
    "Who was Erwin Schrodinger?",
    "Describe Dennis Ritchie's C programming language",
    "Who is Geoffrey Hinton?",
    "Tell me about Karen Sparck Jones' IR contributions",
    "Who was Richard Feynman?",
    "Describe Douglas Crockford's JavaScript work",
    "Who is Yoshua Bengio?",
    "Tell me about Hedy Lamarr's frequency hopping",
    "Who was Max Born?",
    "Describe Jeremy Howard's deep learning education",
    "Who is Geoffrey Hinton?",
    "Tell me about Radia Perlman's networking",
    "Who was Werner Heisenberg?",
    "Describe Rachel Thomas' AI fairness work",
    "Who is Yann LeCun?",
    "Tell me about Barbara Liskov's programming principles",
    "Who was Paul Dirac?",
    "Describe Timnit Gebru's AI ethics advocacy",
    "Who is Hinton Geoffrey?",
]
