CHAT_EXAMPLES = [
    "I'm feeling curious about the universe today.",
    "What do you think about the future of technology?",
    "Tell me something that will surprise me.",
    "I had a strange dream last night – can you interpret it?",
    "Do you think artificial intelligence will ever be conscious?",
    "What's the meaning of life, in your opinion?",
    "If you could travel anywhere, where would you go?",
    "I'm trying to decide between two options – can you help me think through them?",
    "What would you do if you had unlimited resources?",
    "Do you ever get bored?",
    "What's your favourite subject to discuss?",
    "Can you recommend a good book to read?",
    "I'm feeling a bit overwhelmed today – can you help me calm down?",
    "What's the most beautiful place you've ever heard of?",
    "If animals could talk, which would be the rudest?",
    "I wonder what it would be like to live on Mars.",
    "What's a skill everyone should learn?",
    "Do you prefer sunrise or sunset?",
    "I've been thinking about starting a new hobby – any suggestions?",
    "What's the best piece of advice you can give?",
    "Is it better to be kind or to be right?",
    "Can you tell me a really good joke?",
    "I'm trying to learn a new language – any tips?",
    "What would happen if the internet stopped working forever?",
    "Do you think time travel will ever be possible?",
    "I'm feeling nostalgic today – talk about the past with me.",
    "What's the most important invention in history?",
    "If you could have dinner with any person, alive or dead, who would it be?",
    "What's something you wish more people understood?",
    "I'm really proud of something I did recently.",
    "What's the scariest thing you know about the universe?",
    "What's your favourite season and why?",
    "Can you describe a perfect day?",
    "I've been feeling unmotivated lately – help me get back on track.",
    "What's the best way to make new friends?",
    "What do you think about social media?",
    "I love exploring new ideas – give me a mind-bending thought.",
    "What's something you've learned from your mistakes?",
    "If you could change one thing about the world, what would it be?",
    "What's the most memorable conversation you've ever had?",
    "I'm just sitting here thinking about how vast the ocean is.",
]