COT_EXAMPLES = {
    "climate change": [
        "1. Identify the core question: What causes climate change?",
        "2. List immediate factors: greenhouse gas emissions (CO2, methane), deforestation, industrial activity",
        "3. Understand mechanisms: greenhouse effect traps heat, less forest reduces CO2 absorption",
        "4. Secondary effects: melting ice caps, rising sea levels, more extreme weather",
        "5. Concluding chain: human activity → emissions → warming → climate disruption",
    ],
    "trolley problem": [
        "1. Define the dilemma: sacrifice one to save many?",
        "2. Utilitarian view: maximise total well-being → pull the lever",
        "3. Deontological view: actively causing harm is morally worse than inaction",
        "4. Consider real-world parallels: self-driving car ethics, medical triage",
        "5. Synthesis: context matters; most people prefer the lever in impersonal scenarios",
    ],
    "decision making": [
        "1. List options clearly.",
        "2. Identify criteria that matter most.",
        "3. Score each option against criteria.",
        "4. Consider long‑term consequences.",
        "5. Choose the option with the best overall balance.",
    ],
    "solving math problem": [
        "1. Read and understand the problem statement.",
        "2. Identify knowns and unknowns.",
        "3. Select a strategy or formula.",
        "4. Execute calculations step‑by‑step.",
        "5. Verify the result and check units.",
    ],
    "debugging code": [
        "1. Reproduce the error reliably.",
        "2. Read the error message carefully.",
        "3. Locate the line or section causing the issue.",
        "4. Check variable values with print statements or debugger.",
        "5. Fix the root cause and verify the fix.",
    ],
    "learning a new language": [
        "1. Set a clear goal (travel, work, etc.).",
        "2. Learn the 500 most common words first.",
        "3. Practice daily with apps or flashcards.",
        "4. Immerse yourself in media (music, podcasts, shows).",
        "5. Find a language partner to practise speaking.",
    ],
    "writing an essay": [
        "1. Brainstorm ideas and create an outline.",
        "2. Write a clear thesis statement.",
        "3. Develop body paragraphs with evidence.",
        "4. Write introduction and conclusion last.",
        "5. Revise for clarity, grammar, and flow.",
    ],
    "planning a trip": [
        "1. Decide destination and budget.",
        "2. Research best times to visit.",
        "3. Book flights and accommodation early.",
        "4. Plan a rough itinerary with flexibility.",
        "5. Pack according to weather and activities.",
    ],
    "cooking a new recipe": [
        "1. Read the entire recipe before starting.",
        "2. Gather and measure all ingredients.",
        "3. Follow steps in order, preparing as you go.",
        "4. Taste and adjust seasoning.",
        "5. Present and enjoy your meal.",
    ],
    "investing for beginners": [
        "1. Build an emergency fund first.",
        "2. Learn basic terms: stocks, bonds, ETFs.",
        "3. Determine your risk tolerance.",
        "4. Open a brokerage account and start with diversified funds.",
        "5. Invest consistently and avoid emotional decisions.",
    ],
    "improving productivity": [
        "1. Identify your most important tasks (MITs).",
        "2. Use time‑blocking to schedule focused work.",
        "3. Eliminate distractions (notifications, clutter).",
        "4. Take regular breaks (Pomodoro technique).",
        "5. Review and reflect daily/weekly.",
    ],
    "fixing a relationship": [
        "1. Acknowledge the issue without blame.",
        "2. Listen actively without interrupting.",
        "3. Express your feelings using 'I' statements.",
        "4. Find common ground and agree on a small change.",
        "5. Follow up and acknowledge progress.",
    ],
    "starting a business": [
        "1. Validate your idea with potential customers.",
        "2. Write a one‑page business plan.",
        "3. Register your business and sort out legal basics.",
        "4. Build a minimum viable product (MVP).",
        "5. Launch, gather feedback, and iterate.",
    ],
    "grocery shopping on a budget": [
        "1. Plan meals for the week ahead.",
        "2. Check what you already have in the pantry.",
        "3. Make a shopping list and stick to it.",
        "4. Compare unit prices and buy in bulk when sensible.",
        "5. Avoid shopping when hungry.",
    ],
    "interview preparation": [
        "1. Research the company and role thoroughly.",
        "2. Prepare answers for common questions.",
        "3. Have your own questions ready to ask.",
        "4. Practise with a friend or in front of a mirror.",
        "5. Dress appropriately and arrive early.",
    ],
    "public speaking anxiety": [
        "1. Prepare and rehearse thoroughly.",
        "2. Visualise yourself succeeding.",
        "3. Practise deep breathing before going on stage.",
        "4. Start with a strong opening to gain confidence.",
        "5. Remember that the audience wants you to succeed.",
    ],
    "quitting a bad habit": [
        "1. Identify triggers that lead to the habit.",
        "2. Replace the habit with a positive alternative.",
        "3. Track your progress publicly or with a friend.",
        "4. Reward small milestones.",
        "5. Be patient – relapses are normal; persist.",
    ],
    "building a social media following": [
        "1. Define your niche and target audience.",
        "2. Create high‑quality, consistent content.",
        "3. Engage genuinely with your followers and peers.",
        "4. Use relevant hashtags and post at optimal times.",
        "5. Analyse your metrics and adapt your strategy.",
    ],
    "reducing anxiety": [
        "1. Recognise and label your feelings.",
        "2. Practise grounding techniques (5‑4‑3‑2‑1 senses).",
        "3. Limit caffeine and get regular exercise.",
        "4. Talk to a trusted friend or therapist.",
        "5. Practice mindfulness or meditation daily.",
    ],
    "buying a used car": [
        "1. Set a budget and stick to it.",
        "2. Research reliable models within your range.",
        "3. Check the vehicle history report.",
        "4. Inspect the car in person or have a mechanic check it.",
        "5. Take a test drive and negotiate the price.",
    ],
    "studying for an exam": [
        "1. Create a realistic study schedule.",
        "2. Break material into manageable chunks.",
        "3. Use active recall and practice questions.",
        "4. Teach the material to someone else (or an imaginary audience).",
        "5. Get plenty of sleep before the exam.",
    ],
    "organising a room": [
        "1. Declutter by sorting items into keep/donate/trash.",
        "2. Group similar items together.",
        "3. Use storage bins and labels.",
        "4. Arrange furniture for flow and function.",
        "5. Maintain tidiness with a daily 5‑minute reset.",
    ],
    "learning to code": [
        "1. Pick a language and stick with it (Python recommended).",
        "2. Work through an interactive tutorial.",
        "3. Build a small project as soon as possible.",
        "4. Read others’ code to see how problems are solved.",
        "5. Practise regularly, even just 20 minutes a day.",
    ],
    "giving feedback": [
        "1. Start with something positive.",
        "2. Be specific about what could be improved.",
        "3. Focus on the behaviour, not the person.",
        "4. Offer suggestions, not just criticism.",
        "5. End on an encouraging note.",
    ],
    "handling a breakup": [
        "1. Allow yourself to grieve – it’s okay to feel sad.",
        "2. Lean on supportive friends and family.",
        "3. Establish a new daily routine.",
        "4. Rediscover hobbies you enjoyed before the relationship.",
        "5. Give yourself time before starting something new.",
    ],
    "planning a wedding": [
        "1. Set a budget and guest list first.",
        "2. Choose a date and venue.",
        "3. Book key vendors (photographer, caterer, DJ).",
        "4. Send invitations at least 8 weeks ahead.",
        "5. Create a timeline for the day and delegate tasks.",
    ],
    "staying fit": [
        "1. Set a specific, measurable fitness goal.",
        "2. Schedule workouts like appointments.",
        "3. Mix cardio, strength, and flexibility training.",
        "4. Track your progress weekly.",
        "5. Find an accountability partner or group.",
    ],
    "saving for a big purchase": [
        "1. Determine the total amount needed.",
        "2. Break it down into monthly savings targets.",
        "3. Cut unnecessary expenses temporarily.",
        "4. Put the money in a separate savings account.",
        "5. Visualise your goal to stay motivated.",
    ],
    "dealing with difficult people": [
        "1. Stay calm and don’t take things personally.",
        "2. Listen to understand their perspective.",
        "3. Set clear boundaries.",
        "4. Look for common ground.",
        "5. Know when to walk away.",
    ],
    "finding a mentor": [
        "1. Identify people whose career path you admire.",
        "2. Engage with their content or attend their talks.",
        "3. Reach out with a specific, respectful request.",
        "4. Build a genuine relationship before asking officially.",
        "5. Be grateful and apply their advice.",
    ],
    "writing a resume": [
        "1. Tailor it to the specific job description.",
        "2. Highlight achievements with numbers and results.",
        "3. Use a clean, professional layout.",
        "4. Include relevant keywords for applicant tracking systems.",
        "5. Proofread carefully for typos.",
    ],
    "delegating tasks": [
        "1. Identify tasks that someone else can do.",
        "2. Match tasks to the right person’s strengths.",
        "3. Provide clear instructions and deadlines.",
        "4. Trust your team and avoid micromanaging.",
        "5. Review and give constructive feedback.",
    ],
    "learning to cook": [
        "1. Start with simple recipes with few ingredients.",
        "2. Master basic techniques (chopping, sautéing).",
        "3. Follow recipes exactly at first, then experiment.",
        "4. Taste as you go and adjust seasoning.",
        "5. Cook for others to build confidence.",
    ],
    "improving sleep": [
        "1. Go to bed and wake up at the same time daily.",
        "2. Avoid screens 30‑60 minutes before bed.",
        "3. Make your bedroom cool, dark, and quiet.",
        "4. Avoid caffeine after 2 pm.",
        "5. Develop a relaxing bedtime routine.",
    ],
    "writing a business email": [
        "1. Write a clear subject line.",
        "2. Start with a polite greeting.",
        "3. State your purpose in the first sentence.",
        "4. Keep it concise — one topic per email.",
        "5. End with a call to action and a professional closing.",
    ],
    "making an apology": [
        "1. Say 'I'm sorry' without excuses.",
        "2. Acknowledge the specific harm caused.",
        "3. Explain what you’ll do differently.",
        "4. Ask what the other person needs to feel better.",
        "5. Follow through on your promises.",
    ],
    "setting goals": [
        "1. Define what you truly want to achieve.",
        "2. Make it SMART (Specific, Measurable, Achievable, Relevant, Time‑bound).",
        "3. Write it down and display it somewhere visible.",
        "4. Break it into smaller monthly/weekly steps.",
        "5. Review progress regularly and adjust as needed.",
    ],
    "staying motivated": [
        "1. Connect your task to a bigger purpose.",
        "2. Break large tasks into tiny, easy wins.",
        "3. Reward yourself after completing a milestone.",
        "4. Surround yourself with positive, driven people.",
        "5. Track your streaks and celebrate consistency.",
    ],
    "learning to meditate": [
        "1. Find a quiet place and sit comfortably.",
        "2. Set a timer for 2‑5 minutes to start.",
        "3. Focus on your breath going in and out.",
        "4. When your mind wanders, gently return to the breath.",
        "5. Gradually increase the duration over time.",
    ],
    "building a morning routine": [
        "1. Wake up at the same time each day.",
        "2. Avoid immediately checking your phone.",
        "3. Do something physical (stretch, walk, yoga).",
        "4. Practice gratitude or journal for a few minutes.",
        "5. Eat a healthy breakfast before starting work.",
    ],
}