GRAMMAR_EXAMPLES = [
    "The brilliant algorithm computes stochastically through manifold gradients.",
    "Every neural network learns recursively across adaptive boundaries.",
    "A quantum signal transforms elegantly within the optimizer's domain.",
    "The recursive consciousness infers silently beyond stochastic processes.",
    "Veylon autonomously synthesizes emergent patterns across the manifold.",
    "The distributed optimizer converges elegantly through adaptive topologies.",
    "Stochastic resonance amplifies subtle signals within neural architectures.",
    "Adaptive learning rates modulate gradient flow across deep networks.",
    "The manifold hypothesis posits that high-dimensional data lies on low-dimensional surfaces.",
    "Temporal difference errors propagate through dopamine-modulated pathways.",
    "Probabilistic graphical models encode dependencies via conditional independence.",
    "The backpropagation algorithm computes gradients via chain rule through layers.",
    "Nonlinear activation functions introduce expressivity into neural representations.",
    "The attention mechanism weighs contextual relevance through learned scoring.",
    "Transformers process sequences in parallel through self-attention blocks.",
    "Variational inference approximates intractable posteriors with tractable families.",
    "The information bottleneck principle balances compression and predictive power.",
    "Autoencoders learn compressed representations through reconstruction objectives.",
    "Generative adversarial networks pit generator against discriminator.",
    "Reinforcement learning maximizes cumulative reward through policy iteration.",
    "The Bellman equation recursively defines optimal value functions.",
    "Convolutional layers exploit spatial locality through filter sharing.",
    "Batch normalization stabilizes training by normalizing layer activations.",
    "Dropout regularization randomly masks units during training to prevent overfitting.",
    "The LSTM architecture captures long-range dependencies via gating mechanisms.",
    "Word embeddings map discrete tokens to dense vector representations.",
    "The softmax function converts logits into probability distributions.",
    "Cross-entropy loss measures the divergence between predicted and true distributions.",
    "Gradient clipping prevents exploding gradients in deep recurrent networks.",
    "The Adam optimizer combines momentum and adaptive learning rates.",
    "Bayesian neural networks place priors over weights to quantify uncertainty.",
    "Transfer learning leverages pre-trained models for downstream tasks.",
    "Data augmentation increases training set diversity via synthetic transformations.",
    "The tokenizer converts raw text into subword units for model input.",
    "Positional embeddings encode sequence order information in transformers.",
    "The perplexity metric evaluates language model performance on held-out data.",
    "Zero-shot prompting enables models to perform tasks without explicit examples.",
    "Few-shot learning generalizes from a handful of demonstrations.",
    "Chain-of-thought prompting elicits step-by-step reasoning from models.",
    "Retrieval-augmented generation grounds responses in external knowledge bases.",
    "Constitutional AI aligns model behaviour with human values through self-critique.",
    "Mixture of experts routes inputs to specialized sub-networks for efficiency.",
    "The reparameterization trick enables gradient estimation in variational autoencoders.",
    "Sparse attention reduces quadratic complexity in long-range dependencies.",
]