IMAGEGEN_EXAMPLES = [
    "fractal galaxy with neon blue and purple",
    "crystal cave glowing with warm golden light",
    "cyberpunk city at night with rain and neon signs",
    "serene Japanese garden with cherry blossoms",
    "mandala pattern electric green on dark background",
    "wave ocean abstract blue and cyan flowing patterns",
    "cosmic spiral bright white and violet stars",
    "flame organic orange and red flowing fire",
    "forest natural green deep mysterious mood",
    "circuit board digital futuristic geometric lines",
    "mountain landscape dramatic sunset orange and pink",
    "snowy village quiet white and soft blue shadows",
    "underwater coral reef vibrant fish and sunlight rays",
    "rose garden close-up soft petals morning dew",
    "storm lightning powerful dark sky electric white",
    "meadow wildflowers spring colorful soft light",
    "urban street day warm sun and long shadows",
    "ice palace frozen blue and crystal white spires",
    "volcano eruption fiery red and ash clouds dramatic",
    "desert dunes golden smooth curves deep shadows",
    "waterfall jungle lush green moss misty cascade",
    "library old books dusty warm lamps wood shelves",
    "space station orbiting Earth stars reflected windows",
    "dragon cave treasure piles glowing with magic",
    "train steam locomotive vintage iron sunset prairie",
    "harbor boats fishing nets morning fog harbor",
    "clockwork gears brass and copper mechanical intricate",
    "autumn path leaves falling orange red brown",
    "lightning bugs summer evening magic warm glow",
    "temple ruins ancient stones moss jungle ancient",
    "butterfly wings close-up blue and black iridescent",
    "castle medieval towers flags green hills moat",
    "market spice colorful piles sacks exotic scents",
    "aurora borealis sky green and purple arctic night",
    "zebra herd savannah golden grass dust sunrise",
    "carnival night lights ferris wheel neon festive crowd",
    "monastery mountain peak clouds sunrise silence",
    "koi pond water reflections stone lantern ripples",
    "grand piano concert hall spotlight alone elegant",
    "lighthouse storm waves crashing rocky cliff beacon",
]