MATH_EXAMPLES = {
    "derivative": "To find the derivative, use the power rule: d/dx x^n = n*x^(n-1).",
    "quadratic formula": "x = (-b ± sqrt(b²-4ac)) / 2a",
    "pythagorean theorem": "a² + b² = c²",
    "area of circle": "Area = π * r²",
    "circumference": "Circumference = 2 * π * r",
    "compound interest": "A = P(1 + r/n)^(nt)",
    "simple interest": "SI = P * r * t",
    "factorial": "n! = n × (n-1) × ... × 1",
    "gcd": "Euclidean algorithm: while b != 0: a, b = b, a % b. Result is a.",
    "lcm": "LCM(a,b) = |a*b| / GCD(a,b)",
    "mean": "Mean = (sum of all values) / (number of values)",
    "median": "Median = middle value of sorted data (or avg of two middle values).",
    "mode": "Mode = most frequently occurring value in a data set.",
    "standard deviation": "σ = sqrt( Σ(xi - μ)² / N )",
    "variance": "Variance = σ²",
    "fibonacci": "F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2)",
    "sine": "sin(θ) = opposite / hypotenuse",
    "cosine": "cos(θ) = adjacent / hypotenuse",
    "tangent": "tan(θ) = sin(θ) / cos(θ) = opposite / adjacent",
    "euler": "e^(iπ) + 1 = 0",
    "logarithm": "log_b(a) = c means b^c = a",
    "natural log": "ln(x) = log_e(x)",
    "exponential growth": "y = a * e^(kt)",
    "pythagorean identities": "sin²θ + cos²θ = 1",
    "distance formula": "d = sqrt((x2-x1)² + (y2-y1)²)",
    "slope": "slope = (y2 - y1) / (x2 - x1)",
    "midpoint": "M = ((x1+x2)/2, (y1+y2)/2)",
    "area of triangle": "Area = 1/2 * base * height",
    "area of rectangle": "Area = length * width",
    "volume of cylinder": "V = π * r² * h",
    "volume of sphere": "V = 4/3 * π * r³",
    "surface area of cube": "SA = 6 * a²",
    "decimal to binary": "Divide by 2 and record remainders in reverse.",
    "binary to decimal": "Sum of digit * 2^position (from right, starting at 0).",
    "permutation": "P(n,r) = n! / (n-r)!",
    "combination": "C(n,r) = n! / (r!(n-r)!)",
    "binomial theorem": "(x + y)^n = Σ C(n,k) x^(n-k) y^k",
    "sum of arithmetic series": "S = n/2 * (a1 + an)",
    "sum of geometric series": "S = a * (1 - r^n) / (1 - r)  (|r| < 1)",
    "probability": "P(A) = number of favourable outcomes / total outcomes",
    "conditional probability": "P(A|B) = P(A∩B) / P(B)",
    "bayes theorem": "P(A|B) = P(B|A) * P(A) / P(B)",
    "expected value": "E(X) = Σ x_i * P(x_i)",
    "z-score": "z = (x - μ) / σ",
    "law of sines": "a/sin(A) = b/sin(B) = c/sin(C)",
    "law of cosines": "c² = a² + b² - 2ab*cos(C)",
    "determinant 2x2": "det([[a,b],[c,d]]) = a*d - b*c",
    "determinant 3x3": "Sarrus' rule: sum of products of main diagonals minus sum of anti-diagonals.",
    "matrix multiplication": "C[i][j] = Σ A[i][k] * B[k][j]",
    "eigenvalue": "Solve det(A - λI) = 0 for λ",
}