VISION_EXAMPLES = [
    "A bright, high-contrast landscape with blue sky and green fields.",
    "A dark, moody portrait with warm tones and soft lighting.",
    "A busy city street with neon signs and light trails at night.",
    "A peaceful garden with low contrast and natural earthy colours.",
    "An abstract composition with dominant reds and high edge density.",
    "A snowy mountain peak against a pale blue sky.",
    "A crowded market with vibrant textiles and sharp details.",
    "A minimalist interior with white walls and soft shadows.",
    "A starry night sky over a calm lake, with cool blue tones.",
    "A close-up of a blooming flower with intricate petal texture.",
    "A rustic wooden cabin in autumn with orange and yellow foliage.",
    "A futuristic laboratory with chrome surfaces and holographic displays.",
    "A golden hour beach scene with gentle waves and warm light.",
    "A dense forest with rays of sunlight piercing through fog.",
    "A dramatic thunderstorm over a wheat field, with dark clouds.",
    "A macro shot of a butterfly wing showing iridescent scales.",
    "A vintage train station with sepia tones and low contrast.",
    "An aerial view of a winding river through a green valley.",
    "A neon-drenched cyberpunk alley with rain and reflections.",
    "A calm Zen garden with raked sand patterns and a single bonsai.",
    "A bustling kitchen in a restaurant with steam and motion blur.",
    "A portrait of an elderly person with deep wrinkles and kind eyes.",
    "A silhouette of a dancer against a warm sunset backdrop.",
    "A high-speed photograph of a splash of water frozen in time.",
    "A misty morning in a lavender field with soft purple hues.",
    "A glowing bioluminescent cave with neon blue and green light.",
    "A classic black-and-white street photography shot with strong contrast.",
    "A colourful coral reef teeming with fish and bright coral structures.",
    "A derelict industrial building with rust and peeling paint.",
    "A child playing in a fountain on a hot summer day.",
    "A geometric abstract design with intersecting triangles and gradients.",
    "A frosty window with intricate ice crystal patterns.",
    "A massive library with towering shelves and warm reading lamps.",
    "A lone tree on a hill under a starry galaxy sky.",
    "A busy construction site with steel beams and heavy machinery.",
    "A delicate watercolour painting of a bridge and reflecting water.",
    "A panoramic view of a canyon during golden hour.",
    "A vivid macro photo of dew drops on a spider web.",
    "A fashion runway show with dramatic spotlight and silhouettes.",
    "A quiet winter village with snow-covered roofs and smoke from chimneys.",
]