# mainData.py – central data file for Veylon AGI v4.0

SYNONYMS = {
    "calculate": ["compute","evaluate","find","determine","work out"],
    "create":    ["build","make","generate","write","construct","produce"],
    "explain":   ["describe","define","elaborate","discuss","clarify"],
    "think":     ["reason","analyze","consider","reflect","ponder"],
    "search":    ["find","look up","query","research","investigate"],
    "generate":  ["produce","create","output","make","synthesize"],
    "image":     ["picture","photo","artwork","illustration","painting","visual"],
    "draw":      ["paint","create","generate","illustrate","render","depict"],
    "function":  ["method","procedure","routine","subroutine"],
    "algorithm": ["method","approach","technique","procedure"],
    "sentence":  ["phrase","text","utterance","statement"],
    "simple":    ["basic","easy","straightforward","elementary"],
    "fast":      ["efficient","quick","rapid","optimized"],
    "neural":    ["deep learning","artificial neural","layered"],
    "gradient":  ["derivative","slope","direction"],
    "brainstorm":["ideate","think of","generate ideas for","explore"],
    "optimize":  ["improve","enhance","tune","refine","search"],
}

INTENT_KEYWORDS = {
    "greet":    ["hello","hi","hey","greetings","morning","evening","good"],
    "who":      ["who","name","describe","yourself","built","veylon","gpt","mofa"],
    "math":     ["sin","cos","sqrt","log","factorial","primes","gcd","calculate"],
    "search":   ["what is","who is","how does","explain","search","define"],
    "code":     ["write","create","build","function","class","python","implement","code"],
    "grammar":  ["sentence","phrase","grammar","generate","random"],
    "cot":      ["step by step","chain of thought","reason","cot","systematic"],
    "tot":      ["tree of thought","perspectives","tot","multiple","branches"],
    "brainstorm":["brainstorm","deep","multi-lens","lenses","explore"],
    "rag":      ["rag","retrieve","knowledge base","augmented","generation"],
    "optimize": ["minimize","maximize","pso","optimize","swarm","particle"],
    "learn":    ["learn","remember","memorize","store","note","fact","knowledge"],
    "predict":  ["predict","classify","intent","probability","inference"],
    "config":   ["config","setting","parameter","mode","temperature","configure"],
    "chat":     ["movie","weather","tired","curious","feeling","talk","discuss"],
    "react":    ["react","multi step","agent","multi-step","investigate"],
    "vision":   ["vision","image","analyze","picture","photo","color","brightness"],
    "explearn": ["explearn","teach","explanatory","triple","question","explanation"],
    "critique": ["critique","cai","constitutional","review","principles","check"],
    "imagegen": ["imagegen","generate","image","draw","paint","create","artwork","cppn","neural","picture"],
}

DEFAULT_SEED = [
    "hello hi hey greetings morning evening good afternoon",
    "who are you name yourself veylon architecture gpt mofa",
    "math sin cos sqrt log factorial primes gcd comb",
    "search what is who is explain define describe",
    "code python function class algorithm script implement",
    "sentence phrase grammar generate text random",
    "think step chain thought reason cot",
    "tree thoughts tot perspectives multiple ways explore",
    "brainstorm deep multi-lens explore ideas topic",
    "rag retrieve knowledge base augmented generation",
    "minimize maximize optimize pso genetic swarm",
    "learn remember store memorize note teach fact",
    "predict intent probability classify label category",
    "config settings parameters mode configure update",
    "chat talk discuss help interesting enjoy",
    "react agent multi step search analyze reason",
    "vision image analyze describe look picture photo",
    "explearn teach question explanation answer triple",
    "critique cai constitutional self review check",
    "imagegen generate draw paint create picture artwork cppn neural",
]

TRAINING_DATA = {
    "greet":     ["Hello there","Hi Veo","Hey good morning","Good afternoon","Greetings AI",
                  "hello veylon","hey assistant","hi there","good day","morning","what's up",
                  "hi how are you","good evening AI","hi can you help me"],
    "who":       ["Who are you","What is your name","Tell me about yourself","What kind of AI",
                  "Who built you","Describe yourself","What can you do","What is mofa",
                  "explain your architecture","what gpt model are you","how many experts"],
    "math":      ["2+3*4","sin(pi/2)","cos(0)","sqrt(144)","log(100)","factorial(10)",
                  "comb(10,3)","gcd(48,36)","isprime(97)","primes(20)","mean([1,2,3])","pi*2"],
    "search":    ["What is the capital of France","Who invented the telephone",
                  "How does photosynthesis work","What is quantum computing",
                  "what is deep learning","explain transformer architecture",
                  "who discovered gravity","what is blockchain"],
    "code":      ["write a python sorting function","create a fibonacci generator",
                  "build a binary search","implement a linked list","write a quicksort",
                  "implement BFS traversal","create a hash map","write async functions"],
    "grammar":   ["Generate a random sentence","Make a sentence","grammar","random sentence",
                  "generate structured sentence","create grammatically correct sentence"],
    "cot":       ["Think step by step about climate change","chain of thought reasoning",
                  "step by step solution","cot what causes inflation","reason carefully"],
    "tot":       ["Tree of thoughts about AI","tot brainstorm solutions","explore multiple paths",
                  "tot reasoning about ethics","consider all branches of thought"],
    "brainstorm":["brainstorm artificial general intelligence","deep brainstorm consciousness",
                  "brainstorm renewable energy","multi-lens analysis","brainstorm solutions"],
    "rag":       ["rag what is quantum mechanics","retrieve and generate about evolution",
                  "rag search climate change","knowledge base neural networks"],
    "optimize":  ["Minimize f(x)=x squared","PSO minimize objective","swarm optimize x^2+sin(x)",
                  "Find global minimum","Maximize reward function","pso search"],
    "learn":     ["learn Python is a great language","learn Machine learning is powerful",
                  "remember this fact","note that water boils at 100 degrees",
                  "memorize pi equals 3.14159","store this knowledge"],
    "predict":   ["predict artificial intelligence","show intent probabilities","classify this",
                  "what is the intent","show model output","run inference"],
    "config":    ["config learning_rate 0.001","config auto_search on","config","settings",
                  "show settings","update configuration","config n_gpt_layers 6"],
    "chat":      ["I really enjoyed that movie","Tell me something interesting",
                  "I am feeling tired","What do you think about music","This is fascinating",
                  "Let us talk about philosophy","I find AI very interesting"],
    "react":     ["react how does photosynthesis work","react explain quantum entanglement",
                  "multi step reasoning about AI","react analyze climate change"],
    "vision":    ["analyze this image","describe image","vision analyze",
                  "what do you see in this picture","analyze image from url"],
    "explearn":  ["explearn What is gravity? | Gravity is force | F=mg",
                  "teach: What is DNA? | Double helix | genetic code",
                  "explearn show my store","explearn test"],
    "critique":  ["critique my response","cai review this","constitutional AI analysis",
                  "self-critique this","review my explanation","cai self-critique"],
    "imagegen":  ["imagegen a futuristic city at sunset","generate image of a dragon",
                  "draw a mountain landscape","paint a portrait","generate a galaxy image",
                  "create image of a forest","imagegen neon cyberpunk","cppn generate nature",
                  "neural image generation of ocean","ai draw abstract art",
                  "generate picture of a robot","imagegen fractal mandala",
                  "draw a crystal cave with glowing lights","ai paint a sci-fi space station"],
}

# Leave this empty unless you want to add extra intent labels
INTENT_LABELS_EXTRA = []