INTENT = "code"
EXAMPLES = [
    "write a python function to reverse a string",
    "debug this javascript loop",
    "how do i implement a binary search tree in C++",
    "create a REST API endpoint in Flask",
    "explain this regex pattern",
    "refactor this code to be more efficient",
    "write a SQL query to join three tables",
    "how to handle exceptions in Java",
    "create a React component for a login form",
    "what's wrong with my for loop",
    "implement quicksort in Python",
    "write a function to validate email addresses",
    "how do I use async/await in JavaScript",
    "create a class for a linked list",
    "write unit tests for this function",
    "optimize this database query",
    "how to use git branches",
    "implement a singleton pattern in Python",
    "write a bash script to backup files",
    "create a Dockerfile for a Node.js app",
    "how do I parse JSON in Python",
    "write a function to find duplicates in an array",
    "implement bubble sort algorithm",
    "create a CSS grid layout",
    "how to use decorators in Python",
    "write a regular expression to match phone numbers",
    "debug this memory leak",
    "implement a hash table from scratch",
    "create a web scraper with BeautifulSoup",
    "how to use promises in JavaScript",
    "write a function to calculate fibonacci numbers",
    "implement dependency injection in C#",
    "create an authentication middleware",
    "how to optimize React renders",
    "write a SQL stored procedure",
    "implement a graph traversal algorithm",
    "create a custom hook in React",
    "how to use lambda functions in Python",
    "write a function to merge sorted arrays",
    "implement a queue using stacks",
    "create a responsive navbar with CSS",
    "how to use generators in Python",
    "write a MongoDB aggregation pipeline",
    "implement the observer pattern",
    "create a RESTful API with Express",
    "how to handle CORS errors",
    "write a function to check if a string is a palindrome",
    "implement binary search algorithm",
    "create a Vue.js component",
    "how to use context in React",
    "write a Python decorator for timing functions",
    "implement a trie data structure",
    "create a WebSocket server",
    "how to use TypeScript interfaces",
    "write a function to flatten a nested array",
    "implement merge sort algorithm",
    "create a CI/CD pipeline with GitHub Actions",
    "how to use Redux in React",
    "write a function to validate credit card numbers",
    "implement a LRU cache",
    "create a GraphQL schema",
    "how to use virtual environments in Python",
    "write a function to rotate a matrix",
    "implement depth-first search",
    "create a middleware in Express",
    "how to use closures in JavaScript",
    "write a SQL query with subqueries",
    "implement the factory pattern",
    "create a form validation in JavaScript",
    "how to use list comprehensions in Python",
    "write a function to find the longest substring",
    "implement breadth-first search",
    "create a Django model with relationships",
    "how to use map, filter, reduce in JavaScript",
    "write a function to check balanced parentheses",
    "implement a priority queue",
    "create a custom validator in Django",
    "how to use sessions in Express",
    "write a function to convert Roman numerals",
    "implement the strategy pattern",
    "create a pagination component",
    "how to use inheritance in Python",
    "write a SQL query to find nth highest salary",
    "implement a bloom filter",
    "create a rate limiter middleware",
    "how to use arrow functions in JavaScript",
    "write a function to detect cycles in a linked list",
    "implement the command pattern",
    "create a search autocomplete feature",
    "how to use context managers in Python",
    "write a function to find all permutations",
    "implement dijkstra's algorithm",
    "create a file upload handler",
    "how to use promises chaining",
    "write a function to solve sudoku",
    "implement A* pathfinding algorithm",
    "create a infinite scroll component",
    "how to use metaclasses in Python",
    "write a function to compress strings",
    "implement the adapter pattern",
    "create a dark mode toggle",
    "how to use async iterators in JavaScript",
    "write a function to find missing number in array",
    "implement a red-black tree",
    "create a shopping cart with Redux",
    "how to use multiple inheritance in Python",
    "write a SQL query for pivot tables",
    "implement the builder pattern",
    "create a drag and drop interface",
    "how to use proxy in JavaScript",
    "write a function to reverse a linked list",
    "implement topological sort",
    "create a real-time chat application",
    "how to use descriptors in Python",
    "write a function to find intersection of arrays",
    "implement the prototype pattern",
    "create a modal component in React",
    "how to use symbols in JavaScript",
    "write a function to calculate power set",
    "implement Kruskal's algorithm",
    "create a authentication system with JWT",
    "how to use abstract classes in Python",
    "write a SQL query for running totals",
    "implement the chain of responsibility pattern",
    "create a carousel slider component",
    "how to use WeakMap in JavaScript",
    "write a function to find longest common subsequence",
    "implement Prim's algorithm",
    "create a multi-step form",
    "how to use __slots__ in Python",
    "write a function to serialize a binary tree",
    "implement the flyweight pattern",
    "create a dropdown menu with keyboard navigation",
    "how to use BigInt in JavaScript",
    "write a SQL query for recursive CTEs",
    "implement union-find data structure",
    "create a tooltip component",
    "how to use property decorators in Python",
    "write a function to find median of two sorted arrays",
    "implement segment tree",
    "create a skeleton loader component",
    "how to use optional chaining in JavaScript",
    "write a function to solve N-Queens problem",
    "implement a B-tree",
    "create a notification system",
    "how to use dataclasses in Python",
    "write a function to calculate edit distance",
    "implement suffix array",
    "create a calendar component",
    "how to use nullish coalescing in JavaScript",
    "write a SQL window function query",
    "implement the memento pattern",
    "create a tabs component",
    "how to use async context managers in Python",
    "write a function to find all anagrams",
    "implement a skip list",
    "create a breadcrumb navigation",
    "how to use dynamic imports in JavaScript",
    "write a function to solve knapsack problem",
    "implement the visitor pattern",
    "create a progress bar component",
    "how to use type hints in Python",
    "write a function to parse expressions",
    "implement a fenwick tree",
    "create a accordion component",
    "how to use private class fields in JavaScript",
    "write a SQL query to find duplicates",
    "implement the interpreter pattern",
    "create a stepper component",
    "how to use protocol in Python",
    "write a function to validate parentheses variants",
    "implement a suffix tree",
    "create a chip input component",
    "how to use top-level await in JavaScript",
    "write a function to find shortest path in matrix",
    "implement the state pattern",
    "create a rating component",
    "how to use structural pattern matching in Python",
    "write a SQL query for median calculation",
    "implement a splay tree",
    "create a color picker component",
    "how to use import.meta in JavaScript",
    "write a function to solve word break problem",
    "implement the template method pattern",
    "create a image cropper component",
    "how to use async generators in Python",
    "write a function to find longest palindromic substring",
    "implement a treap",
    "create a file explorer component",
    "how to use logical assignment operators in JavaScript",
    "write a SQL query for percentile calculation",
    "implement the bridge pattern",
    "create a kanban board component",
    "how to use match statement in Python 3.10",
    "write a function to serialize and deserialize tree",
    "implement a AVL tree",
    "create a mentions input component",
    "how to use string replaceAll in JavaScript",
    "write a function to find all paths in graph",
    "implement the composite pattern",
    "create a timeline component",
    "how to use union types in Python",
    "write a SQL query for moving averages",
    "implement a rope data structure",
    "create a gantt chart component",
    "how to use at method for arrays in JavaScript",
    "write a function to solve traveling salesman",
    "implement the decorator pattern in Java",
    "create a spreadsheet component",
    "how to use ParamSpec in Python",
    "write a function to find bridge edges in graph",
    "implement a radix tree",
    "create a virtual scrolling list",
    "how to use Object.hasOwn in JavaScript",
    "write a SQL query for cohort analysis",
    "implement the proxy pattern",
    "create a tree view component",
    "how to use TypedDict in Python",
    "write a function to find articulation points",
    "implement a k-d tree",
    "create a data table with sorting and filtering",
    "how to use error cause in JavaScript",
    "write a function to solve coin change problem",
    "implement the facade pattern",
    "create a command palette component",
    "how to use Literal types in Python",
    "write a SQL query for funnel analysis",
    "implement a quad tree",
    "create a split pane component",
    "how to use array findLast in JavaScript",
    "write a function to detect strongly connected components",
    "implement disjoint set with path compression",
    "create a code editor component",
    "how to use Self type in Python",
    "write a function to solve subset sum problem",
    "implement a persistent data structure",
    "create a masonry layout component",
    "how to use array toSorted in JavaScript",
    "write a SQL query for retention analysis",
    "implement the iterator pattern",
    "create a rich text editor",
    "how to use Never type in Python",
    "write a function to find minimum spanning tree",
    "implement a rope data structure for text editing",
    "create a diagram editor component",
    "how to use hashbang grammar in JavaScript",
    "write a function to solve job scheduling problem",
    "implement lazy evaluation in Python",
    "create a chart component with zoom",
    "how to use private methods in JavaScript classes",
    "write a SQL query for customer lifetime value",
    "implement a concurrent hash map",
    "create a audio waveform visualizer",
    "how to use Concatenate in Python typing",
    "write a function to find maximal rectangle",
    "implement copy-on-write semantics",
    "create a video player with controls",
    "how to use static initialization blocks in JavaScript",
    "write a function to solve regex matching",
    "implement a lock-free queue",
    "create a pdf viewer component",
    "how to use Final in Python",
    "write a SQL query for churn prediction prep",
    "implement a concurrent skip list",
    "create a 3D model viewer component",
    "how to use numeric separators in JavaScript",
    "write a function to find longest increasing path",
    "implement a B+ tree",
    "create a syntax highlighting editor",
    "how to use ClassVar in Python",
    "write a function to solve wildcard matching",
    "implement a lock-free stack",
    "create a flow diagram builder",
    "how to use regexp match indices in JavaScript",
    "write a SQL query for RFM analysis",
    "implement a concurrent trie",
    "create a markdown editor with preview",
    "how to use Annotated in Python",
    "write a function to find maximum flow",
    "implement a persistent vector",
    "create a whiteboard component",
    "how to use class static blocks in JavaScript",
    "write a function to solve regular expression with wildcards",
    "implement a bloom filter with counting",
    "create a mind map component"
]