INTENT = "imagegen"
EXAMPLES = [
    "generate an image of a sunset over mountains",
    "create a picture of a cat wearing a hat",
    "make an image of a futuristic city",
    "draw a portrait of a person",
    "generate a landscape with a river",
    "create an image of a dragon",
    "make a picture of a coffee cup",
    "draw a fantasy castle",
    "generate an abstract art piece",
    "create an image of a vintage car",
    "make a picture of outer space",
    "draw a tropical beach scene",
    "generate an image of a robot",
    "create a winter wonderland scene",
    "make a picture of a flower garden",
    "analyze this image for me",
    "what's in this picture",
    "describe this image",
    "what do you see in this photo",
    "identify the objects in this image",
    "what colors are in this picture",
    "is there a person in this image",
    "what is the main subject of this photo",
    "tell me about this image",
    "extract text from this image",
    "read the text in this picture",
    "what does the sign say in this image",
    "transcribe the text from this photo",
    "is this image appropriate",
    "detect faces in this image",
    "how many people are in this photo",
    "what emotions are shown in this image",
    "is this image safe for work",
    "categorize this image",
    "what style is this artwork",
    "is this a painting or photograph",
    "when was this image taken",
    "where was this photo taken",
    "what landmarks are in this image",
    "generate a logo for my company",
    "create a poster design",
    "make an image for social media",
    "draw a comic book character",
    "generate a photorealistic portrait",
    "create an image in anime style",
    "make a watercolor painting",
    "draw in the style of Van Gogh",
    "generate a minimalist design",
    "create a steampunk themed image",
    "make a cyberpunk cityscape",
    "draw a medieval battle scene",
    "generate an image of mythical creatures",
    "create a horror themed picture",
    "make an image of underwater life",
    "draw a space station",
    "generate a product mockup",
    "create an isometric illustration",
    "make a pixel art character",
    "draw a vector graphic",
    "generate a 3D render",
    "create a low poly landscape",
    "make a vaporwave aesthetic image",
    "draw a cottagecore scene",
    "generate a dark academia aesthetic",
    "create a surrealist painting",
    "make an impressionist landscape",
    "draw a cubist portrait",
    "generate an art nouveau design",
    "create a retro 80s style image",
    "make a neon sign design",
    "draw a mandala pattern",
    "generate a geometric pattern",
    "create a seamless texture",
    "make a background for desktop",
    "draw a fantasy map",
    "generate a book cover design",
    "create an album cover art",
    "make a t-shirt design",
    "draw a tattoo design",
    "generate a sticker design",
    "create an infographic design",
    "make a meme image",
    "draw a character sheet",
    "generate concept art",
    "create environment art",
    "make a storyboard frame",
    "draw an architectural rendering",
    "generate interior design visualization",
    "create a fashion design sketch",
    "make a jewelry design",
    "draw a vehicle design",
    "generate a weapon design",
    "create creature concept art",
    "make a prop design",
    "what breed is this dog",
    "identify this plant species",
    "what type of bird is this",
    "recognize this landmark",
    "what car model is this",
    "identify this artwork",
    "who is the artist of this painting",
    "what architectural style is this",
    "identify this flag",
    "what logo is this",
    "read this handwriting",
    "what language is this text",
    "translate the text in this image",
    "is this image edited",
    "detect photoshop in this image",
    "is this a deepfake",
    "find similar images",
    "reverse image search",
    "where can I buy this product",
    "what brand is this",
    "how much is this worth",
    "is this authentic or fake",
    "what year is this from",
    "identify the location in this image",
    "what's the weather in this photo",
    "what time of day is this",
    "what season is shown here",
    "is this indoors or outdoors",
    "estimate the size of this object",
    "what material is this made of",
    "is this image high quality",
    "what is the resolution of this image",
    "convert this image to black and white",
    "upscale this image",
    "enhance this photo",
    "remove background from this image",
    "crop this image",
    "resize this picture",
    "add a filter to this image",
    "adjust the brightness",
    "increase contrast",
    "make this image sharper",
    "blur the background",
    "remove red eye from this photo",
    "fix the lighting in this image",
    "restore this old photo",
    "colorize this black and white image",
    "remove this object from the image",
    "add text to this picture",
    "put a watermark on this image",
    "combine these two images",
    "create a collage from these photos",
    "make a gif from these images",
    "extract frames from this gif",
    "convert this image format",
    "compress this image file",
    "generate an image of a happy puppy",
    "create a picture of northern lights",
    "make an image of a cozy cabin",
    "draw a magical forest",
    "generate a steaming bowl of ramen",
    "create an image of cherry blossoms",
    "make a picture of a lighthouse",
    "draw a bustling marketplace",
    "generate an image of galaxy spiral",
    "create a thunderstorm scene",
    "make a picture of ancient ruins",
    "draw a peaceful zen garden",
    "generate an image of bioluminescent ocean",
    "create a foggy mountain path",
    "make a picture of autumn leaves",
    "draw a field of lavender",
    "generate an image of northern forest",
    "create a desert oasis scene",
    "make a picture of coral reef",
    "draw a waterfall in jungle",
    "generate an image of floating islands",
    "create a mushroom fairy ring",
    "make a picture of starry night sky",
    "draw a Japanese tea ceremony",
    "generate an image of Viking ship",
    "create a Egyptian pyramid scene",
    "make a picture of Roman colosseum",
    "draw a samurai warrior",
    "generate an image of pirate ship",
    "create a wild west saloon",
    "make a picture of ninja in shadow",
    "draw a knight in armor",
    "generate an image of wizard casting spell",
    "create an elf archer",
    "make a picture of dwarf blacksmith",
    "draw a mermaid underwater",
    "generate an image of phoenix rising",
    "create a unicorn in meadow",
    "make a picture of griffin",
    "draw a basilisk",
    "generate an image of kraken",
    "create a werewolf transformation",
    "make a picture of vampire castle",
    "draw a zombie apocalypse",
    "generate an image of alien planet",
    "create a spaceship interior",
    "make a picture of mech robot",
    "draw a time machine",
    "generate an image of portal",
    "create a holographic interface",
    "make a picture of flying car",
    "draw a underwater city",
    "generate an image of sky city",
    "create a crystal cave",
    "make a picture of lava flows",
    "draw an ice palace",
    "generate an image of tree house",
    "create a secret garden",
    "make a picture of ancient library",
    "draw a alchemist laboratory",
    "generate an image of witch cottage",
    "create a haunted mansion",
    "make a picture of abandoned asylum",
    "draw a creepy carnival",
    "generate an image of misty graveyard",
    "create a dark forest path",
    "make a picture of mysterious fog",
    "draw a shadowy figure",
    "generate an image of glowing eyes",
    "create a blood moon",
    "make a picture of eclipse",
    "draw a comet passing earth",
    "generate an image of meteor shower",
    "create a supernova explosion",
    "make a picture of black hole",
    "draw a nebula cloud",
    "generate an image of space colony",
    "create a Mars base",
    "make a picture of Earth from space",
    "draw a satellite",
    "generate an image of astronaut floating",
    "create a rocket launch",
    "make a picture of lunar landing",
    "draw a space walk",
    "generate an image of alien encounter",
    "create a UFO sighting",
    "make a picture of crop circles",
    "draw an observatory",
    "generate an image of telescope view",
    "create a planetarium interior",
    "make a picture of star constellation",
    "draw a zodiac symbol",
    "generate an image of solar system",
    "create a planet rings closeup",
    "make a picture of Jupiter storm",
    "draw Saturn's hexagon",
    "generate an image of Venus surface",
    "create Mars rovers",
    "make a picture of Europa ocean",
    "draw Titan's lakes",
    "generate an image of Pluto heart",
    "create asteroid belt",
    "make a picture of Kuiper belt",
    "draw Oort cloud",
    "generate an image of exoplanet",
    "create a binary star system",
    "make a picture of pulsar",
    "draw a quasar",
    "generate an image of magnetar",
    "create a white dwarf star",
    "make a picture of red giant",
    "draw a blue supergiant",
    "generate an image of neutron star",
    "create a gamma ray burst",
    "make a picture of dark matter visualization",
    "draw a gravitational wave",
    "generate an image of wormhole",
    "create a multiverse concept",
    "make a picture of quantum realm",
    "draw a string theory visualization",
    "generate an image of tesseract",
    "create a fourth dimension concept",
    "make a picture of time dilation",
    "draw a Mobius strip",
    "generate an image of Klein bottle",
    "create a fractal pattern",
    "make a picture of sacred geometry",
    "draw a golden ratio spiral",
    "generate an image of Fibonacci sequence",
    "create a impossible object",
    "make a picture of optical illusion",
    "draw a MC Escher style",
    "generate an image of paradox stairs",
    "create a Salvador Dali inspired scene"
]