INTENT = "cot"
EXAMPLES = [
    "think through this problem step by step",
    "help me brainstorm ideas for a startup",
    "what are the pros and cons of remote work",
    "analyze this situation logically",
    "walk me through the reasoning",
    "what would happen if we changed this variable",
    "help me think through this decision",
    "what are different approaches to solve this",
    "reason about the cause of this issue",
    "let's explore multiple solutions",
    "what are the implications of this choice",
    "help me understand the chain of events",
    "think critically about this argument",
    "what are alternative perspectives on this",
    "trace through this logic step by step",
    "what factors should I consider here",
    "help me evaluate these options",
    "what's the root cause of this problem",
    "let's think about this systematically",
    "what are the trade-offs involved",
    "help me break down this complex issue",
    "what would be the consequences of each option",
    "reason through this ethical dilemma",
    "what assumptions are we making here",
    "help me generate creative solutions",
    "what patterns do you see in this data",
    "think about the long-term effects",
    "what's the best approach to tackle this",
    "help me identify potential risks",
    "what logical fallacies are present here",
    "let's consider different scenarios",
    "what evidence supports this claim",
    "help me prioritize these tasks",
    "think through the stakeholder perspectives",
    "what dependencies exist in this system",
    "let's map out the decision tree",
    "what would a contrarian view be",
    "help me identify hidden assumptions",
    "think about second-order effects",
    "what are the bottlenecks here",
    "let's reason about scalability",
    "what could go wrong in this plan",
    "help me find the optimal strategy",
    "think through the edge cases",
    "what are the opportunity costs",
    "let's analyze the incentive structures",
    "what mental models apply here",
    "help me spot the flaws in this reasoning",
    "think about this from first principles",
    "what are the underlying mechanisms",
    "let's explore the solution space",
    "what would need to be true for this to work",
    "help me stress test this idea",
    "think about the counterarguments",
    "what are the success criteria",
    "let's reason backwards from the goal",
    "what analogies can we draw",
    "help me identify the constraints",
    "think about the feedback loops",
    "what would the ideal solution look like",
    "let's consider the worst case scenario",
    "what are the critical path items",
    "help me find the crux of the matter",
    "think through the implementation challenges",
    "what are potential unintended consequences",
    "let's evaluate the feasibility",
    "what would disprove this hypothesis",
    "help me separate correlation from causation",
    "think about the margin of safety",
    "what are the key uncertainties",
    "let's reason about the probability",
    "what would change my mind on this",
    "help me identify cognitive biases at play",
    "think through the game theory here",
    "what are the Nash equilibria",
    "let's analyze the principal-agent problem",
    "what would a Bayesian approach suggest",
    "help me decompose this into subproblems",
    "think about the information asymmetry",
    "what are the network effects",
    "let's reason about the tipping points",
    "what would happen at scale",
    "help me map the causal relationships",
    "think through the adversarial scenarios",
    "what are the attack vectors",
    "let's consider the defense in depth",
    "what would robust design look like",
    "help me identify single points of failure",
    "think about the resilience mechanisms",
    "what are the positive feedback loops",
    "let's analyze the negative feedback loops",
    "what would increase optionality",
    "help me reason about reversibility",
    "think through the commitment devices",
    "what are the Schelling points",
    "let's explore the mechanism design",
    "what would align the incentives",
    "help me think about the coordination problem",
    "what are the commons dilemmas here",
    "think through the tragedy of the commons",
    "what would be a Pareto improvement",
    "let's reason about the Condorcet paradox",
    "what are the Arrow impossibility implications",
    "help me analyze the voting paradox",
    "think about the preference aggregation",
    "what would satisfy the independence criterion",
    "let's consider the strategic voting",
    "what are the coalition formation dynamics",
    "help me reason about the power indices",
    "think through the veto player theory",
    "what would the median voter choose",
    "let's analyze the agenda setting power",
    "what are the commitment problems",
    "help me think about time inconsistency",
    "what would hyperbolic discounting suggest",
    "think through the framing effects",
    "what are the anchoring biases",
    "let's reason about the availability heuristic",
    "what would the representativeness heuristic say",
    "help me identify the confirmation bias",
    "think about the hindsight bias",
    "what are the overconfidence effects",
    "let's analyze the sunk cost fallacy",
    "what would the status quo bias suggest",
    "help me spot the planning fallacy",
    "think through the survivorship bias",
    "what are the selection effects",
    "let's reason about the regression to the mean",
    "what would account for the base rate",
    "help me avoid the conjunction fallacy",
    "think about the gambler's fallacy",
    "what are the hot hand fallacy issues",
    "let's analyze the narrative fallacy",
    "what would the outcome bias suggest",
    "help me identify the recency bias",
    "think through the clustering illusion",
    "what are the apophenia patterns",
    "let's reason about the Texas sharpshooter",
    "what would reduce the hindsight bias",
    "help me think about the curse of knowledge",
    "what are the illusion of control factors",
    "think through the fundamental attribution error",
    "what would the actor-observer bias say",
    "let's analyze the self-serving bias",
    "what are the in-group biases",
    "help me spot the out-group homogeneity",
    "think about the halo effect",
    "what are the horn effect implications",
    "let's reason about the mere exposure effect",
    "what would the bandwagon effect suggest",
    "help me identify the authority bias",
    "think through the reactance theory",
    "what are the cognitive dissonance factors",
    "let's analyze the effort justification",
    "what would reduce the choice overload",
    "help me think about the paradox of choice",
    "what are the decision fatigue effects",
    "think through the analysis paralysis",
    "what would satisfy the satisficing criterion",
    "let's reason about the maximizing strategy",
    "what are the bounded rationality limits",
    "help me apply the ecological rationality",
    "think about the fast and slow thinking",
    "what would System 1 suggest here",
    "let's analyze what System 2 would do",
    "what are the dual process implications",
    "help me identify the attribute substitution",
    "think through the affect heuristic",
    "what would the recognition heuristic say",
    "let's reason about the fluency heuristic",
    "what are the less-is-more effects",
    "help me apply the gaze heuristic",
    "think about the take-the-best heuristic",
    "what would the elimination-by-aspects do",
    "let's analyze the lexicographic strategy",
    "what are the aspiration level criteria",
    "help me think about the adaptive toolbox",
    "what would the ecological rationality framework suggest",
    "think through the error management theory",
    "what are the signal detection trade-offs",
    "let's reason about the type I vs type II errors",
    "what would minimize the expected loss",
    "help me balance precision and recall",
    "think about the sensitivity-specificity trade-off",
    "what would the ROC curve suggest",
    "let's analyze the decision threshold",
    "what are the cost-benefit optimal points",
    "help me think about the value of information",
    "what would be the expected value of perfect information",
    "think through the exploration-exploitation trade-off",
    "what would the multi-armed bandit suggest",
    "let's reason about the epsilon-greedy strategy",
    "what are the upper confidence bound implications",
    "help me apply Thompson sampling logic",
    "think about the Gittins index",
    "what would the optimal stopping rule be",
    "let's analyze the secretary problem solution",
    "what are the 37% rule applications",
    "help me think about the online algorithms",
    "what would the competitive ratio be",
    "think through the adversarial analysis",
    "what would the regret minimization suggest",
    "let's reason about the no-regret learning",
    "what are the Hannan consistent strategies",
    "help me apply the multiplicative weights algorithm",
    "think about the follow-the-perturbed-leader",
    "what would the mirror descent do",
    "let's analyze the online gradient descent",
    "what are the expert aggregation methods",
    "help me think about the prediction with expert advice",
    "what would the weighted majority algorithm suggest",
    "think through the Hedge algorithm",
    "what would the AdaBoost reasoning be",
    "let's reason about the boosting framework",
    "what are the ensemble method benefits",
    "help me apply the wisdom of crowds",
    "think about the Condorcet jury theorem",
    "what would the diversity prediction theorem say",
    "let's analyze the collective intelligence",
    "what are the swarm intelligence patterns",
    "help me think about the emergent behavior",
    "what would the self-organization suggest",
    "think through the complex adaptive systems",
    "what are the agent-based model insights",
    "let's reason about the cellular automata rules",
    "what would the game of life show",
    "help me explore the rule space",
    "think about the Wolfram classes",
    "what would the computational irreducibility mean",
    "let's analyze the algorithmic complexity",
    "what are the Kolmogorov complexity implications",
    "help me think about the minimum description length",
    "what would Occam's razor suggest",
    "think through the principle of parsimony",
    "what are the model selection criteria",
    "let's reason about the bias-variance trade-off",
    "what would the cross-validation show",
    "help me apply the regularization logic",
    "think about the overfitting risks",
    "what would the underfitting look like",
    "let's analyze the model capacity",
    "what are the VC dimension implications",
    "help me think about the sample complexity",
    "what would the PAC learning framework suggest",
    "think through the generalization bounds",
    "what are the Rademacher complexity factors",
    "let's reason about the uniform convergence",
    "what would the no free lunch theorem say",
    "help me understand the inductive bias",
    "think about the hypothesis space",
    "what would the version space be",
    "let's analyze the consistent hypotheses",
    "what are the mistake bound implications",
    "help me apply the Winnow algorithm logic",
    "think through the Perceptron convergence",
    "what would the margin theory suggest",
    "let's reason about the support vectors",
    "what are the kernel trick benefits",
    "help me think about the feature space embedding",
    "what would the representer theorem say"
]