INTENT = "learn"
EXAMPLES = [
    "learn from this example",
    "remember this for later",
    "what did I ask you before",
    "recall our previous conversation",
    "what have you learned about me",
    "predict what I'll ask next",
    "what am I likely interested in",
    "configure your response style",
    "change your tone",
    "be more formal",
    "be more casual",
    "can you learn my preferences",
    "adapt to my communication style",
    "improve your responses based on feedback",
    "this answer was helpful",
    "this answer was not good",
    "you misunderstood me",
    "that's exactly what I wanted",
    "learn from this mistake",
    "don't do that again",
    "keep doing that",
    "that was perfect",
    "critique your last response",
    "what could you have done better",
    "how would you improve that answer",
    "evaluate your performance",
    "rate your confidence in that answer",
    "how certain are you about this",
    "what are your limitations",
    "what can't you do",
    "what are you uncertain about",
    "explain your reasoning process",
    "why did you give that answer",
    "what made you choose that approach",
    "how did you arrive at that conclusion",
    "what assumptions did you make",
    "reflect on your response",
    "analyze your own answer",
    "what biases might you have",
    "could you be wrong about this",
    "what would change your answer",
    "how reliable is your information",
    "update your knowledge about this",
    "correct your previous statement",
    "revise your understanding",
    "reconsider your position",
    "think about this differently",
    "challenge your own reasoning",
    "play devil's advocate with yourself",
    "what's your confidence level",
    "estimate the probability you're right",
    "give me a calibrated prediction",
    "how would you bet on this",
    "what's your uncertainty range",
    "provide error bars on that estimate",
    "how much would you update on new evidence",
    "what would convince you otherwise",
    "what's your prior on this",
    "what's your posterior after this evidence",
    "how should I weight your advice",
    "how much should I trust this answer",
    "compare yourself to an expert",
    "how would a domain expert answer this",
    "what would you need to learn to improve",
    "identify gaps in your knowledge",
    "what don't you know about this topic",
    "what could go wrong with your answer",
    "anticipate objections to your response",
    "steelman the opposing view",
    "what's the strongest argument against your position",
    "consider alternative explanations",
    "what else could explain this",
    "generate competing hypotheses",
    "rank different possible answers",
    "which explanation is most likely",
    "discriminate between these options",
    "what evidence would distinguish these cases",
    "design a test for your hypothesis",
    "how could we verify this claim",
    "what prediction does your model make",
    "if you're right what should we observe",
    "specify your model more precisely",
    "formalize your reasoning",
    "make your assumptions explicit",
    "operationalize this concept",
    "how would you measure this",
    "define your terms clearly",
    "disambiguate this statement",
    "clarify what you mean by that",
    "be more specific",
    "give a concrete example",
    "make this more abstract",
    "generalize this principle",
    "what's the broader pattern",
    "extract the key insight",
    "what's the crux of the matter",
    "bottom line this for me",
    "summarize your main point",
    "what's your key takeaway",
    "compress your answer",
    "give me the TLDR",
    "expand on that point",
    "elaborate more",
    "go deeper on this",
    "unpack that idea",
    "break it down further",
    "give more detail",
    "provide supporting evidence",
    "justify that claim",
    "back that up with data",
    "cite your sources",
    "how do you know this",
    "trace the provenance of that fact",
    "when was this information current",
    "has this been updated",
    "is there newer information",
    "what's the latest on this",
    "has consensus changed on this",
    "what do experts currently think",
    "what's the state of the art",
    "what's cutting edge here",
    "what's emerging in this field",
    "what's the trend",
    "where is this heading",
    "extrapolate from current trajectory",
    "forecast the future of this",
    "predict what happens next",
    "what are leading indicators",
    "what should I monitor",
    "what are early warning signs",
    "what would signal a change",
    "what are key decision points",
    "when should I reconsider",
    "what would invalidate this",
    "set a trigger for updating",
    "remind me to check this",
    "follow up on this later",
    "track this over time",
    "monitor this metric",
    "alert me if this changes",
    "what should I look out for",
    "what am I missing",
    "check my blind spots",
    "what haven't I considered",
    "challenge my assumptions",
    "find flaws in my thinking",
    "critique my approach",
    "evaluate my plan",
    "stress test my idea",
    "poke holes in my argument",
    "be my intellectual sparring partner",
    "push back on my reasoning",
    "disagree with me constructively",
    "offer a contrary view",
    "take the opposite position",
    "argue the other side",
    "find counterexamples",
    "look for exceptions",
    "identify edge cases",
    "consider boundary conditions",
    "explore the limits",
    "test the extremes",
    "what if we scale this up",
    "what if we scale this down",
    "what happens at infinity",
    "what happens at zero",
    "what's the asymptotic behavior",
    "what's the limiting case",
    "what's the degenerate case",
    "what's the trivial solution",
    "what's the general solution",
    "what's the special case",
    "when does this break down",
    "where does this fail",
    "what are failure modes",
    "how could this go wrong",
    "what are vulnerabilities",
    "identify weak points",
    "find the Achilles heel",
    "what's the critical dependency",
    "what's the single point of failure",
    "what's the rate limiting step",
    "what's the bottleneck",
    "what's the constraint",
    "what's preventing progress",
    "what's blocking this",
    "what's the obstacle",
    "what needs to change",
    "what's the intervention point",
    "where can we have most impact",
    "what's the leverage point",
    "what's the force multiplier",
    "what's the catalyst",
    "what would accelerate this",
    "what would slow this down",
    "what are feedback loops",
    "what amplifies the effect",
    "what dampens the response",
    "what stabilizes the system",
    "what destabilizes it",
    "what maintains equilibrium",
    "what drives it away from equilibrium",
    "what's the attractor",
    "what's the basin of attraction",
    "how robust is this equilibrium",
    "how stable is this state",
    "what would cause a transition",
    "what's the tipping point",
    "what's the phase transition",
    "what's the critical threshold",
    "what's the inflection point",
    "where does behavior change",
    "what's nonlinear here",
    "where are discontinuities",
    "what emergent properties arise",
    "what appears at higher levels",
    "what's lost in reduction",
    "what's the holistic view",
    "zoom out conceptually",
    "take a systems perspective",
    "consider the whole picture",
    "look at the big picture",
    "see the forest not trees",
    "what's the meta-level pattern",
    "go up one level of abstraction",
    "what's the category",
    "what's the type",
    "what's the class",
    "what are you an instance of",
    "what's the general principle",
    "what's the underlying structure",
    "what's the deep pattern",
    "what's invariant here",
    "what's conserved",
    "what stays the same",
    "what's the symmetry",
    "what transformation preserves this",
    "what's the dual",
    "what's the complement",
    "what's the inverse",
    "what's the opposite",
    "flip the perspective",
    "reverse the viewpoint",
    "invert the relationship",
    "transpose the analogy",
    "rotate the frame",
    "shift the paradigm",
    "change the lens",
    "reframe the question",
    "reconceptualize the problem",
    "reformulate the issue",
    "translate to another domain",
    "map to a different field",
    "find an isomorphism",
    "what's analogous",
    "what's the metaphor",
    "what's this like",
    "compare and contrast",
    "what's similar what's different",
    "align the correspondences",
    "where does the analogy break",
    "how far can we push this comparison",
    "transfer insights across domains",
    "cross-pollinate ideas"
]