INTENT = "react"
EXAMPLES = [
    "react how does photosynthesis work",
    "react explain quantum entanglement",
    "react what is the meaning of life",
    "react analyze climate change",
    "multi step reasoning about AI safety",
    "agent mode for complex problems",
    "react search and reason consciousness",
    "multi step answer for this",
    "reason and search about vaccines",
    "react explain evolution",
    "multi step reasoning for ethics",
    "react: what causes inflation",
    "react search: history of quantum computing",
    "multi-step agent: explain machine learning",
    "react mode: analyze renewable energy",
    "react investigate: dark matter",
    "agent loop: research artificial intelligence",
    "react and search: climate solutions",
    "multi step: what is the Fermi paradox",
    "react: how do black holes work",
    "agent: research the history of mathematics",
    "multi step reasoning: what is consciousness",
    "react investigate blockchain technology",
    "react research: CRISPR gene editing",
    "agent mode: explain neuroplasticity",
    "react: what is quantum supremacy",
    "multi step: analyze the trolley problem",
    "react search and synthesize: free will",
    "agent loop for: future of AI research",
    "react: how does the immune system work",
    "multi step agent: explain relativity simply",
    "react reason through: the nature of time",
    "react: investigate the origin of language",
    "agent mode reasoning: economic inequality",
    "react analyze: social media effects on society",
]