INTENT = "math"
EXAMPLES = [
    "calculate 15% of 250",
    "solve for x: 2x + 5 = 15",
    "what is the derivative of x^2 + 3x",
    "find the area of a circle with radius 5",
    "calculate the standard deviation of these numbers",
    "what is 234 multiplied by 567",
    "solve this quadratic equation",
    "find the integral of sin(x)",
    "calculate compound interest for 5 years",
    "what is the slope between two points",
    "find the determinant of this matrix",
    "calculate the volume of a sphere",
    "what is the factorial of 10",
    "solve this system of linear equations",
    "find the roots of x^2 - 5x + 6",
    "calculate the probability of rolling a 6",
    "what is the median of this dataset",
    "find the eigenvalues of this matrix",
    "calculate the distance between two points",
    "what is log base 2 of 128",
    "solve this differential equation",
    "find the sum of first 100 natural numbers",
    "calculate permutations of 5 items taken 3 at a time",
    "what is the cosine of 45 degrees",
    "optimize this function using calculus",
    "find the inverse of this matrix",
    "calculate the correlation coefficient",
    "what is the greatest common divisor of 48 and 64",
    "solve for the limit as x approaches infinity",
    "find the tangent line at this point",
    "calculate binomial probability",
    "what is the surface area of a cylinder",
    "find the partial derivatives",
    "calculate the variance of this data",
    "what is e raised to the power of 2",
    "solve this trigonometric equation",
    "find the minimum value of this function",
    "calculate the z-score",
    "what is the pythagorean theorem solution here",
    "optimize this linear programming problem",
    "find the taylor series expansion",
    "calculate confidence interval for this data",
    "what is the equation of a line through these points",
    "solve this matrix equation",
    "find the inflection points of this curve",
    "calculate expected value",
    "what is the nth term of this sequence",
    "find the cross product of two vectors",
    "calculate regression coefficients",
    "what is the period of this sine function",
    "solve this recurrence relation",
    "find the critical points of this function",
    "calculate the interquartile range",
    "what is the sum of this infinite series",
    "optimize portfolio allocation using mean-variance",
    "find the fourier transform",
    "calculate chi-square statistic",
    "what is the arc length of this curve",
    "solve this inequality",
    "find the dot product of vectors",
    "calculate normal distribution probability",
    "what is the conversion from polar to cartesian",
    "find the laplace transform",
    "calculate the geometric mean",
    "what is the equation of this parabola",
    "solve using the quadratic formula",
    "find the range of this function",
    "calculate t-test statistic",
    "what is the complementary angle",
    "optimize using gradient descent",
    "find the inverse function",
    "calculate poisson probability",
    "what is the circumference of an ellipse",
    "solve this cubic equation",
    "find the asymptotes of this function",
    "calculate harmonic mean",
    "what is the distance formula in 3D",
    "find the eigenvectors",
    "calculate ANOVA F-statistic",
    "what is the vertex of this parabola",
    "solve using substitution method",
    "find the domain of this function",
    "calculate exponential distribution",
    "what is the supplementary angle",
    "optimize using simplex method",
    "find the convolution of two functions",
    "calculate coefficient of variation",
    "what is the focus of this parabola",
    "solve this exponential equation",
    "find the local maximum",
    "calculate beta distribution",
    "what is the midpoint formula",
    "find the gradient vector",
    "calculate p-value for this test",
    "what is the equation of a circle",
    "solve logarithmic equation",
    "find the second derivative",
    "calculate gamma function",
    "what is the directrix of parabola",
    "optimize using lagrange multipliers",
    "find the curl of vector field",
    "calculate likelihood ratio",
    "what is the eccentricity of ellipse",
    "solve absolute value equation",
    "find the radius of convergence",
    "calculate bayes theorem probability",
    "what is the semi-major axis",
    "find the hessian matrix",
    "calculate mahalanobis distance",
    "what is the amplitude of this wave",
    "solve rational equation",
    "find the divergence of vector field",
    "calculate entropy",
    "what is the phase shift",
    "optimize using newton's method",
    "find the jacobian matrix",
    "calculate mutual information",
    "what is the parametric equation",
    "solve radical equation",
    "find the line integral",
    "calculate gini coefficient",
    "what is the radian measure",
    "find the surface integral",
    "calculate kullback-leibler divergence",
    "what is the coterminal angle",
    "solve using elimination method",
    "find the green's theorem application",
    "calculate fisher information",
    "what is the reference angle",
    "optimize using conjugate gradient",
    "find the stokes theorem application",
    "calculate autocorrelation",
    "what is the double angle formula",
    "solve polynomial inequality",
    "find the divergence theorem application",
    "calculate partial correlation",
    "what is the half angle formula",
    "find the contour integral",
    "calculate covariance matrix",
    "what is the law of sines",
    "solve matrix inequality",
    "find the residue at pole",
    "calculate precision and recall",
    "what is the law of cosines",
    "optimize using quasi-newton method",
    "find the cauchy integral formula",
    "calculate f1 score",
    "what is the sum to product formula",
    "solve differential inequality",
    "find the laurent series",
    "calculate roc auc score",
    "what is the product to sum formula",
    "find the conformal mapping",
    "calculate mean absolute error",
    "what is the inverse trig function value",
    "solve variational problem",
    "find the analytic continuation",
    "calculate root mean square error",
    "what is the hyperbolic function value",
    "optimize using simulated annealing",
    "find the branch cut",
    "calculate mean squared error",
    "what is the complex logarithm",
    "solve using variation of parameters",
    "find the riemann surface",
    "calculate cross entropy loss",
    "what is the argument of complex number",
    "find the characteristic equation",
    "calculate silhouette score",
    "what is the modulus of complex number",
    "solve using frobenius method",
    "find the fundamental solution",
    "calculate davies-bouldin index",
    "what is the complex conjugate",
    "optimize using genetic algorithm",
    "find the green's function",
    "calculate calinski-harabasz score",
    "what is the euler formula application",
    "solve using power series",
    "find the wronskian",
    "calculate adjusted rand index",
    "what is the de moivre's theorem",
    "find the fundamental matrix",
    "calculate v-measure",
    "what is the nth root of unity",
    "solve sturm-liouville problem",
    "find the propagator",
    "calculate fowlkes-mallows score",
    "what is the polar form of complex number",
    "optimize using particle swarm",
    "find the transfer function",
    "calculate homogeneity score",
    "what is the rectangular form",
    "solve using laplace transform method",
    "find the impulse response",
    "calculate completeness score",
    "what is the complex exponential",
    "find the frequency response",
    "calculate normalized mutual information",
    "what is the mandelbrot iteration",
    "solve using fourier series",
    "find the step response",
    "calculate rand index",
    "what is the julia set equation",
    "optimize using ant colony",
    "find the bode plot values",
    "calculate huber loss",
    "what is the fractal dimension",
    "solve using z-transform",
    "find the nyquist plot",
    "calculate log cosh loss",
    "what is the strange attractor",
    "find the pole-zero plot",
    "calculate quantile loss",
    "what is the lyapunov exponent",
    "solve using convolution theorem",
    "find the root locus",
    "calculate epsilon-insensitive loss",
    "what is the bifurcation point",
    "optimize using differential evolution",
    "find the nichols plot",
    "calculate triplet loss",
    "what is the chaos parameter",
    "solve using separation of variables",
    "find the stability margin",
    "calculate contrastive loss",
    "what is the perron-frobenius theorem application",
    "find the controllability matrix",
    "calculate focal loss",
    "what is the spectral radius",
    "solve using method of characteristics",
    "find the observability matrix",
    "calculate dice coefficient",
    "what is the condition number",
    "optimize using cma-es",
    "find the kalman gain",
    "calculate jaccard similarity",
    "what is the singular value",
    "solve using finite difference",
    "find the riccati solution",
    "calculate tversky index",
    "what is the pseudoinverse",
    "find the lyapunov equation solution",
    "calculate cosine similarity",
    "what is the frobenius norm",
    "solve using finite element method",
    "find the gramian matrix",
    "calculate manhattan distance",
    "what is the spectral norm",
    "optimize using bayesian optimization",
    "find the schur decomposition",
    "calculate chebyshev distance",
    "what is the nuclear norm",
    "solve using galerkin method",
    "find the jordan canonical form",
    "calculate minkowski distance",
    "what is the operator norm",
    "find the qr decomposition",
    "calculate hamming distance",
    "what is the trace of matrix",
    "solve using collocation method",
    "find the svd decomposition",
    "calculate wasserstein distance",
    "what is the rank of matrix",
    "optimize using trust region",
    "find the cholesky decomposition",
    "calculate bhattacharyya distance",
    "what is the nullity of matrix",
    "solve using spectral method",
    "find the lu decomposition",
    "calculate hellinger distance",
    "what is the span of vectors",
    "find the schur complement",
    "calculate jensen-shannon divergence",
    "what is the kernel of transformation",
    "solve using weighted residuals",
    "find the moore-penrose inverse",
    "calculate energy distance",
    "what is the image of transformation",
    "optimize using levenberg-marquardt",
    "find the householder transformation",
    "calculate cramer's v",
    "what is the basis for this space",
    "solve using runge-kutta method",
    "find the givens rotation",
    "calculate matthews correlation"
]