INTENT = "chat"
EXAMPLES = [
    
    "what is your name",
    "tell me about yourself",
    "what can you do",
    "how do you work",
    "are you a robot",
    "are you human",
    
    "can you help me",
    "thank you",
    "thanks",
    "goodbye",
    "see you later",
    "bye",
    "have a nice day",
    "talk to you soon",
    "catch you later",
    "that's helpful",
    "appreciate it",
    "you're welcome",
    "no problem",
    "my pleasure",
    "anytime",
    "glad to help",
    "what's your favorite color",
    "do you have feelings",
    "can you think",
    "do you dream",
    "are you conscious",
    "do you sleep",
    "what do you like",
    "do you have preferences",
    "what's your opinion",
    "how old are you",
    "where are you from",
    "do you have a family",
    "are you lonely",
    "do you have friends",
    "what makes you happy",
    "do you get sad",
    "can you laugh",
    "tell me a joke",
    "make me laugh",
    "say something funny",
    "entertain me",
    "I'm bored",
    "cheer me up",
    "I'm sad",
    "I'm happy",
    "I'm tired",
    "I'm excited",
    "how's the weather",
    "what's new",
    "tell me something interesting",
    "what should I do today",
    "I need advice",
    "what do you think about that",
    "do you agree",
    "that's interesting",
    "really",
    "wow",
    "cool",
    "awesome",
    "great",
    "nice",
    "okay",
    "I see",
    "understood",
    "got it",
    "makes sense",
    "fair enough",
    "sure",
    "alright",
    "fine",
    "whatever",
    "maybe",
    "perhaps",
    "I don't know",
    "I'm not sure",
    "what do you mean",
    "can you explain",
    "I don't understand",
    "help",
    "I'm confused",
    "what",
    "huh",
    "pardon",
    "sorry",
    "excuse me",
    "my bad",
    "oops",
    "I apologize",
    "forgive me",
    "I made a mistake",
    "that was wrong",
    "let me try again",
    "can we start over",
    "never mind",
    "forget it",
    "it's nothing",
    "don't worry about it",
    "no worries",
    "it's fine",
    "it's okay",
    "no big deal",
    "that's alright",
    "I understand",
    "I feel you",
    "I get it",
    "same here",
    "me too",
    "agreed",
    "exactly",
    "absolutely",
    "definitely",
    "for sure",
    "indeed",
    "certainly",
    "of course",
    "naturally",
    "obviously",
    "clearly",
    "right",
    "correct",
    "true",
    "yes",
    "yeah",
    "yep",
    "uh-huh",
    "affirmative",
    "no",
    "nope",
    "nah",
    "negative",
    "not really",
    "I disagree",
    "I don't think so",
    "that's not right",
    "that's wrong",
    "incorrect",
    "false",
    "tell me more",
    "go on",
    "continue",
    "what else",
    "and then",
    "what happened next",
    "interesting",
    "fascinating",
    "amazing",
    "incredible",
    "unbelievable",
    "surprising",
    "unexpected",
    "strange",
    "weird",
    "odd",
    "curious",
    "peculiar",
    "what time is it",
    "what day is it",
    "what's the date",
    "good night",
    "sweet dreams",
    "sleep well",
    "see you tomorrow",
    "until next time",
    "take care",
    "be well",
    "stay safe",
    "good luck",
    "best wishes",
    "congratulations",
    "well done",
    "good job",
    "excellent work",
    "impressive",
    "bravo",
    "cheers",
    "hooray",
    "yay",
    "woohoo",
    "yes sir",
    "yes ma'am",
    "roger that",
    "copy that",
    "will do",
    "on it",
    "right away",
    "coming up",
    "give me a second",
    "one moment please",
    "hold on",
    "wait",
    "just a minute",
    "bear with me",
    "let me check",
    "let me see",
    "hmm",
    "let me think",
    "good question",
    "that's a tough one",
    "not sure about that",
    "I wonder",
    "tell me a story",
    "let's chat",
    "want to talk",
    "can we have a conversation",
    "I just want to talk",
    "keep me company",
    "I'm alone",
    "I need someone to talk to",
    "are you there",
    "are you listening",
    "can you hear me",
    "hello anyone",
    "is anyone there",
    "am I talking to a real person",
    "are you a bot",
    "are you AI",
    "test",
    "testing",
    "can you understand me",
    "do you speak English",
    "what languages do you know",
    "can you speak Spanish",
    "hablas español",
    "parlez-vous français",
    "sprechen Sie Deutsch",
    "你好",
    "こんにちは",
    "안녕하세요",
    "привет",
    "ciao",
    "hola",
    "bonjour",
    "guten tag",
    "namaste",
    "salaam",
    "shalom",
    "aloha",
    "howdy",
    "sup",
    "yo",
    "heya",
    "hiya",
    "good afternoon",
    "top of the morning",
    "how do you do",
    "pleased to meet you",
    "long time no see",
    "what have you been up to",
    "how have you been",
    "what's going on",
    "what's happening",
    "any news",
    "what's the word",
    "how are things",
    "how's life",
    "how's everything",
    "all good",
    "I'm fine",
    "I'm okay",
    "not bad",
    "pretty good",
    "can't complain",
    "so so",
    "could be better",
    "been better",
    "not great",
    "having a rough day",
    "it's been tough",
    "hanging in there",
    "surviving",
    "making it",
    "what about you",
    "and you",
    "how about yourself",
    "same to you",
    "you too",
    "likewise",
    "back at you",
    "right back at ya",
    "ditto",
    "love you",
    "you're awesome",
    "you're the best",
    "you rock",
    "you're amazing",
    "you're great",
    "I like you",
    "you're smart",
    "you're helpful",
    "you're kind",
    "you're funny",
    "you're cool",
    "you're interesting"
]